// AUTO-GENERATED bởi backend cli/gen-legacy-labels.ts — KHÔNG sửa tay.
// Nhãn field hệ cũ pc02hcm.com (từ catalog TruongTuyChinh) cho panel "Dữ liệu gốc hệ cũ".
export const LEGACY_FIELD_LABELS: Record<string, string> = {
  "Noi_luu_tru_bao_quan_ke_bien_phong_toa": "Nơi lưu trữ, bảo quản, kê biên, phong tỏa",
  "Vks_khong_phe_chuan_lenh_giu_nguoi_trong_truong_hop_khan_cap": "VKS không phê chuẩn lệnh giữ người trong trường hợp khẩn cấp",
  "bat_duoc_bao_nhieu_bang_nhom": "Bắt được bao nhiêu băng nhóm",
  "bien_phap_khac_phuc_tdc_vu_an": "Biện pháp, tiến độ khắc phục lý do TĐC vụ án",
  "cac_truong_hop_nguoi_pham_toi_bi_tam_giu": "Chọn các trường hợp người phạm tội bị tạm giữ, tạm giam",
  "can_cu_phuc_hoi_dieu_tra_vu_an": "Căn cứ ra quyết định Phục hồi điều tra vụ án",
  "can_cu_ra_quyet_dinh_dinh_chi_bi_can": "Căn cứ ra QĐ Đình chỉ điều tra bị can",
  "can_cu_ra_quyet_dinh_khong_khoi_to": "Căn cứ để ra Quyết định Không khởi tố",
  "can_cu_tam_dinh_chi_bi_can": "Căn cứ tạm đình chỉ bị can",
  "can_cu_tam_dinh_chi_nguon_tin": "Căn cứ Tạm đình chỉ nguồn tin",
  "can_cu_tam_dinh_chi_vu_an": "Căn cứ tạm đình chỉ vụ án",
  "cho_o_hien_tai_bi_can": "Chổ ở hiện tại",
  "chuyen_vu_an_cho_co_quan_khac": "Đã chuyển vụ án cho CQĐT khác",
  "co_bao_nhieu_bang_nhom": "Xác nhận có băng nhóm",
  "dia-chi-bi-hai": "Địa chỉ cá nhân, cơ quan, tổ chức cung cấp, bị hại",
  "dieu": "Điều luật",
  "dieu_tra_mo_rong": "Điều tra mở rộng",
  "dieu_tra_vien": "Điều tra viên thụ lý",
  "dieu_tra_vien_phuong_xa": "Điều tra viên là trưởng - phó Công an phường thụ lý",
  "dinh_chi_vu_an": "Số Quyết định đình chỉ vụ án",
  "do_vat_tai_lieu_kem_theo": "Đồ vật, tài liệu kèm theo",
  "doi_tuong_co_su_dung_ma_tuy": "Xác nhận Đối tượng có sử dụng chất ma túy",
  "doi_tuong_co_tien_an_tien_su": "Xác nhận Đối tượng có tiền án, tiền sự",
  "doi_tuong_trong_dien_suu_tra": "Xác nhận Đối tượng trong diện sưu tra",
  "don_vi_bao_quan_ho_so": "Đơn vị lưu giữ, bảo quản hồ sơ",
  "don_vi_giai_quyet": "Đơn vị giải quyết",
  "dtv": "Điều tra viên",
  "ghi_am_ghi_hinh_da_duoc_xet_xu": "Xác nhận Trong đó: Số vụ án tiến hành Ghi âm, Ghi hình đã được xét xử",
  "ghi_chu": "Ghi chú",
  "ghi_chu_khac": "Ghi chú khác",
  "ghi_chu_nhap_ho_so": "Ghi chú nhập vào hồ sơ nào",
  "ghi_chu_trung_don": "Ghi chú trùng đơn",
  "gioi_tinh": "Giới tính",
  "ho_khau_thuong_tru_bi_can": "Hộ khẩu thường trú",
  "ho_so_luu": "Số hồ sơ lưu",
  "ho_ten_bi_can": "Họ tên Đối tượng, Bị can",
  "ket_luan_dieu_tra_vu_an": "Số KLĐT đề nghị truy tố",
  "ket_qua_xu_ly_giai_quyet_khac": "Kết quả xử lý, giải quyết khác",
  "khac_phuc_ly_do_tdc": "Biên bản, báo cáo, kế hoạch khắc phục lý do TĐC vụ việc",
  "khac_phuc_tdc_vu_an": "Biên bản, báo cáo, kế hoạch khắc phục lý do TĐC vụ án",
  "kho_khan_vuong": "Khó khăn vướng mắc",
  "ksv": "Kiểm sát viên",
  "lanh_dao_to_tung": "Lãnh đạo phụ trách tố tụng",
  "lenh_nhap_kho": "Lệnh nhập, phiếu nhập kho",
  "lenh_tam_giam_bi_can": "Lệnh tạm giam",
  "lich_su": "Lịch sử chuyển đơn vị",
  "loai_thong_tin": "Loại thông tin",
  "loai_toi_pham": "Phân loại tội phạm (Chỉ xác định sau khi có Quyết định khởi tố vụ án)",
  "ly_do": "Lý do",
  "ly_do_ra_quyet_dinh_khong_khoi_to_vu_an": "Lý do ra Quyết định không khởi tố vụ án",
  "ly_do_tam_dinh_chi": "Lý do tạm đình chỉ",
  "ly_do_tam_dinh_chi_vu_an": "Lý do tạm đình chỉ vụ án",
  "ly_do_tra_ho_so_dieu_tra_bo_sung": "Lý do trả hồ sơ điều tra bổ sung (Khoản 1 Điều 245 Bộ luật TTHS)",
  "nam": "Năm",
  "ngay": "Ngày",
  "ngay-quyet-dinh-tach-hanh-vi": "Ngày Quyết định tách hành vi",
  "ngay_ban_an_co_hieu_luc": "Ngày tháng năm bản án của toà án có hiệu lực",
  "ngay_cap_cccd_nguyen_don": "Ngày cấp CCCD",
  "ngay_cqcsdt_phat_hien_co_dau_hieu_pham_toi": "Ngày CQCSĐT trực tiếp phát hiện có dấu hiệu tội phạm",
  "ngay_dang_ky_ho_so": "Ngày đăng ký hồ sơ nghiệp vụ",
  "ngay_de_xuat": "Ngày đề xuất",
  "ngay_giao_don_vi_giai_quyet": "Ngày giao đơn vị giải quyết",
  "ngay_het_thoi_hieu_truy_cuu_tnhs_vu_an": "Ngày hết thời hiệu truy cứu TNHS vụ án",
  "ngay_ket_luan_dieu_tra": "Ngày Kết luận điều tra vụ án",
  "ngay_lenh_bat_bi_can_de_tam_giam": "Ngày Lệnh bắt bị can để tạm giam",
  "ngay_lenh_tam_giam": "Ngày Lệnh tạm giam",
  "ngay_nguoi_pham_toi_bi_bat_khan_cap": "Ngày Người phạm tội bị giữ trong các trường hợp khẩn cấp",
  "ngay_nguoi_pham_toi_bi_lap_bien_ban_tam_giu_tam_giam": "Ngày người phạm tội bị lập biên bản tạm giữ, tạm giam",
  "ngay_nguoi_pham_toi_dau_thu": "Ngày người phạm tội đầu thú, tự thú",
  "ngay_nhap_vu_an": "Ngày tháng năm nhập vụ án",
  "ngay_nop_luu_ho_so": "Ngày nộp lưu hồ sơ",
  "ngay_pham_toi_qua_tang": "Ngày người phạm tội bị bắt quả tang",
  "ngay_phieu_chuyen": "Ngày phiếu chuyển/ Công văn/ Ủy thác điều tra",
  "ngay_phuc_hoi_dieu_tra_vu_an": "Ngày Quyết định phục hồi điều tra vụ án",
  "ngay_phuc_hoi_nguon_tin_toi_pham": "Ngày Phục hồi nguồn tin tội phạm",
  "ngay_quyet_dinh_dieu_tra_bo_sung_vks": "Ngày trả hồ sơ điều tra bổ sung của Viện kiểm sát",
  "ngay_quyet_dinh_dieu_tra_lai": "Ngày Quyết định điều tra lại",
  "ngay_quyet_dinh_dinh_chi_bi_can": "Ngày Quyết định đình chỉ bị can",
  "ngay_quyet_dinh_dinh_chi_vu_an": "Ngày Quyết định đình chỉ vụ án",
  "ngay_quyet_dinh_khoi_to_bi_can": "Ngày Quyết định Khởi tố bị can",
  "ngay_quyet_dinh_khoi_to_vu_an": "Ngày ra Quyết định Khởi tố vụ án",
  "ngay_quyet_dinh_phuc_hoi_dieu_tra_bi_can": "Ngày Quyết định phục hồi điều tra bị can",
  "ngay_quyet_dinh_tam_dinh_chi_dieu_tra_bi_can": "Ngày Quyết định tạm đình chỉ điều tra bị can",
  "ngay_ra_ket_luan_dieu_tra_bo_sung_gan_nhat": "Ngày ra Kết luận điều tra bổ sung",
  "ngay_ra_quyet_dinh_khoi_to": "Ngày ra quyết định khởi tố",
  "ngay_ra_quyet_dinh_khong_khoi_to": "Ngày ra Quyết định Không khởi tố",
  "ngay_ra_quyet_dinh_phan_cong_tin_bao": "Ngày ra Quyết định phân công giải quyết nguồn tin tội phạm",
  "ngay_ra_quyet_dinh_tam_dinh_chi_nguon_tin": "Ngày ra Quyết định Tạm đình chỉ nguồn tin",
  "ngay_ra_quyet_dinh_tam_giu": "Ngày ra Quyết định tạm giữ",
  "ngay_tach_ho_so": "Ngày Quyết định tách hồ sơ",
  "ngay_tam_dinh_chi_vu_an": "Ngày Quyết định tạm đình chỉ vụ án",
  "ngay_thang_nam_het_thoi_hieu_vu_viec": "Ngày tháng năm hết thời hiệu truy cứu TNHS",
  "ngay_thang_nam_sinh_bi_can": "Ngày tháng năm sinh",
  "ngay_thoi_diem_phan_cong_giai_quyet_to_giac": "Ngày Thời điểm phân công giải quyết tố giác, tin báo",
  "ngay_thong_ke": "Ngày tổng hợp thống kê",
  "ngay_tiep_nhan_an_dtbs": "Ngày tiếp nhận án điều tra bổ sung",
  "ngay_tiep_nhan_nguon_tin": "Ngày tiếp nhận (theo biên bản tiếp nhận nguồn tin)",
  "ngay_tiep_nhan_tin": "Ngày tiếp nhận tin khi đơn vị nhận được",
  "ngay_tra_ho_so_dieu_tra_bo_sung_cua_toa_an": "Ngày trả hồ sơ điều tra bổ sung của Toà án",
  "ngay_viet_don": "Ngày viết đơn",
  "ngay_xay_ra": "Ngày tội phạm xảy ra",
  "nghe_nghiep": "Nghề nghiệp",
  "nghi_van_doi_tuong": "Nghi vấn đối tượng hoặc bị can",
  "nguon_don": "Nguồn đơn/Đơn vị giao",
  "nhan_xet": "Nhận xét",
  "nhap_vao_vu_viec_so": "Nhập vào vụ việc hồ sơ khác",
  "nhom_tuoi": "Nhóm tuổi",
  "noi_cap_cccd_nguyen_don": "Nơi cấp CCCD",
  "noi_dung": "Nội dung",
  "noi_xay_ra": "Nơi xảy ra tội phạm",
  "noi_xay_ra_phuong_xa": "Nơi xảy ra (cấp phường/xã)",
  "phan_loai_dan_su": "Phân loại dân sự",
  "phan_loai_nguon_tin_ban_dau": "Phân loại ban đầu",
  "phan_loai_toi_pham_cong_nghe_cao": "Bấm chọn nễu xác định đây là tội phạm công nghệ cao",
  "phuc_hoi_nguon_tin_toi_pham": "Số Phục hồi nguồn tin tội phạm",
  "phuong_thuc_thu_doan": "Phương thức thủ đoạn",
  "quyet_dinh_dieu_tra_lai": "Số Quyết định điều tra lại",
  "quyet_dinh_dinh_chi_bi_can": "Số Quyết định Đình chỉ Bị can",
  "quyet_dinh_khoi_to_bi_can": "Quyết định Khởi tố bị can",
  "quyet_dinh_khoi_to_vu_an": "Số Quyết định Khởi tố vụ án",
  "quyet_dinh_khong_khoi_to": "Quyết định Không khởi tố",
  "quyet_dinh_nhap_vu_an": "Số Quyết định nhập vụ án",
  "quyet_dinh_phan_cong_giai_quyet_nguon_tin": "Quyết định phân công giải quyết nguồn tin tội phạm",
  "quyet_dinh_phuc_hoi_bi_can": "Số Quyết định phục hồi bị can",
  "quyet_dinh_phuc_hoi_vu_an": "Số Quyết định Phục hồi Vụ án",
  "quyet_dinh_tach_hanh_vi": "Số Quyết định tách hành vi",
  "quyet_dinh_tach_vu_an": "Số Quyết định tách vụ án",
  "quyet_dinh_tam_dinh_chi_dieu_tra_bi_can": "Số Quyết định Tạm đình chỉ bị can",
  "quyet_dinh_tam_dinh_chi_nguon_tin": "Quyết định Tạm đình chỉ nguồn tin",
  "quyet_dinh_tam_dinh_chi_vu_an": "Số Quyết định Tạm đình chỉ vụ án",
  "sinh_nam_nguoi_to_giac": "Sinh năm",
  "so_ban_an_co_hieu_luc": "Số bản án của toàn án có hiệu lực",
  "so_bi_can_co_ghi_am_ghi_hinh": "Số lượng bị can có ghi âm ghi hình",
  "so_bien_ban_ghi_loi_khai_co_ghi_am_ghi_hinh": "Số lượng biên bản ghi lời khai có ghi âm ghi hình",
  "so_cccd_nguyen_don": "Số căn cước công dân",
  "so_dang_ky_ho_so": "Số đăng ký hồ sơ nghiệp vụ",
  "so_dien_thoai_nguyen_don": "Số điện thoại nguyên đơn",
  "so_doi_tuong": "Số đối tượng phạm tội",
  "so_doi_tuong_bi_bat_trong_vu_an_khac": "Số đối tượng bị bắt trong vụ án khác",
  "so_doi_tuong_da_bat": "Số đối tượng bắt được",
  "so_doi_tuong_suu_tra_hiem_nghi": "Số đối tượng sưu tra/hiềm nghi",
  "so_doi_tuong_vi_pham_hanh_chinh": "Số đối tượng vi phạm hành chính",
  "so_ket_luan_dieu_tra_bo_sung_gan_nhat": "Số Kết luận điều tra bổ sung",
  "so_lenh_bat_bi_can_de_tam_giam": "Số Lệnh bắt bị can để tạm giam",
  "so_luong_bi_can_vks_yeu_cau_ghi_am_ghi_hinh": "Số lượng bị can VKS yêu cầu ghi âm ghi hình",
  "so_luong_bi_hai": "Số lượng người bị hại",
  "so_luong_nguoi_bi_phat_tien": "Số người bị phạt tiền",
  "so_luong_nguoi_chet": "Số người chết",
  "so_luong_sung_thu_hoi": "Số lượng súng thu hồi",
  "so_luong_thuoc_no_thu_hoi": "Số lượng thuốc nổ thu hồi",
  "so_nguoi_bi_thuong": "Số người bị thương",
  "so_phieu_chuyen": "Số phiếu chuyển/ Công văn/ Ủy thác điều tra",
  "so_quyet_dinh_dieu_tra_bo_sung": "Số Quyết định điều tra bổ sung",
  "so_quyet_dinh_tam_giu": "Số Quyết định tạm giữ",
  "so_tien_bi_thiet_hai": "Số tiền bị thiệt hại (triệu Việt nam Đồng)",
  "so_tien_thu_hoi": "Số tiền thu hồi được (triệu Việt Nam Đồng)",
  "stt": "Số thứ tự thụ lý (hệ cũ)",
  "stt_cu": "Số thứ tự hồ sơ cũ",
  "su_dung_vu_khi_nong": "Sử dụng vụ khí nóng",
  "tam_dinh_chi_co_quan": "Cơ quan tạm đình chỉ",
  "tam_dinh_chi_so": "Số quyết định tạm đình chỉ",
  "tam_dinh_chi_time": "Ngày tạm đình chỉ",
  "ten_ca_nhan_co_quan_to_chuc_cung_cap": "Tên cá nhân, cơ quan, tổ chức cung cấp, bị hại",
  "thang": "Tháng",
  "thoi_han_thuc_hien_uy_thac_dieu_tra": "Thời hạn thực hiện Uỷ thác điều tra",
  "tien_do_khac_phuc_tdc": "Tiến độ khắc phục TĐC vụ việc",
  "tiep_nhan_nam": "Tiếp nhận năm",
  "tiep_nhan_ngay": "Tiếp nhận ngày",
  "tiep_nhan_so": "Tiếp nhận số",
  "tiep_nhan_thang": "Tiếp nhận tháng",
  "tieu_chi_khac": "Tiêu chí khác",
  "tinh_trang_ho_so": "Tình trạng hồ sơ",
  "toi-danh-ban-dau": "Tội danh cũ trước đây",
  "toi_danh_bi_can": "Tội danh",
  "toi_danh_chinh": "Tội danh chính khi khởi tố",
  "toi_danh_chinh_blhs2015": "Tội danh chính - BLHS 2015 (nhận định ban đầu)",
  "toi_danh_khac": "Tội danh phụ khi khởi tố",
  "tom_tat_noi_dung": "Tóm tắt nội dung",
  "tong_so_bien_ban_ghi_loi_khai": "Tổng số biên bản ghi lời khai",
  "tong_so_bien_ban_hoi_cung_bi_can": "Tổng số biên bản hỏi cung bị can",
  "tong_so_bien_ban_hoi_cung_co_ghi_am_ghi_hinh": "Tổng số biên bản hỏi cung có ghi âm ghi hình",
  "tong_so_tien_phat_hanh_chinh": "Tổng số tiền phạt hành chính (triệu Việt Nam Đồng)",
  "truong_hop_bao_cao_ban_giam_doc": "Trường hợp báo cáo Ban Giám đốc",
  "vat_chung": "Loại, đặc điểm đồ vật, tài liệu, vật chứng",
  "vks_khong_phe_chuan_lenh_bat_bi_can_de_tam_giam": "VKS không phê chuẩn lệnh bắt tạm giam",
  "vks_khong_phe_chuan_lenh_bat_nguoi_bi_giu_trong_truong_hop_khan_cap": "VKS không phê chuẩn lệnh bắt người bị giữ trong trường hợp khẩn cấp",
  "vu_an_co_su_dung_ket_quả_ghi_am_ghi_hinh_trong_xet_xu": "Xác nhận trong đó: Vụ án có sử dụng kết quả Ghi âm ghi hình trong xét xử",
  "vu_an_khong_gagh_nhung_toa_an_yeu_cau_cung_cap_gagh": "Xác nhận trong đó: Vụ án không ghi âm ghi hình nhưng Tòa án yêu cầu cung cấp ghi âm ghi hình",
  "vu_viec_chuyen_don_vi_khac": "Chuyển vụ việc cho đơn vị khác",
  "xac_dinh_vu_viec_tam_dung_giai_quyet": "Xác định vụ việc này là vụ việc tạm dừng giải quyết (trước năm 2015)",
  "xac_nhan_ghi_am_ghi_hinh": "Bấm xác nhận nếu là nguồn tin có sử dụng Ghi âm, Ghi hình",
  "xac_nhan_loi_dieu_tra_vien": "Xác nhận nếu lỗi của Điều tra viên",
  "xac_nhan_loi_kiem_sat_vien": "Xác nhận nếu lỗi của Kiểm sát viên",
  "xac_nhan_neu_cqdt_ban_hanh_vb_de_nghi_vks_tra_ho_so_dtbs": "Xác nhận nếu CQĐT ban hành VB đề nghị VKS trả hồ sơ ĐTBS",
  "xac_nhan_neu_cqdt_ban_hanh_vb_hoan_ho_so_de_tiep_tuc_de_nghi_truy_to": "Xác nhận nếu CQĐT ban hành Văn bản hoàn hồ sơ để tiếp tục đề nghị truy tố",
  "xac_nhan_neu_la_vu_an_ghi_am_ghi_hinh": "Xác nhận nếu là Vụ án có sử dụng Ghi âm, Ghi hình",
  "xac_nhan_vks_yeu_cau_ghi_am_ghi_hinh": "Bấm xác nhận nếu VKS yêu cầu ghi âm ghi hình",
  "xac_nhan_vu_an_da_duoc_xet_xu": "Xác nhận vụ án đã được xét xử",
  "xac_nhan_vu_viec_vphc": "Xác nhận vụ việc có vi phạm hành chính",
};
