// AUTO-GENERATED (dev extract: legacy-mapper + field-parity + form fields).
// Lọc UI để mỗi legacy field hiện/sửa 1 chỗ, KHÔNG đụng DB, KHÔNG sót data.
// COL = key có cột typed; MAIN = field form chính render (đã strip prefix utdt_/stat_...).
export type LegacyEntity = 'petition' | 'incident' | 'case';

const COL: Record<LegacyEntity, string[]> = {
  petition: ["dexuat","diachibihai","dieutravien","dovattailieukemtheo","ghichukhac","ghichutrungdon","ketquaxulygiaiquyetkhac","lanhdaototung","loaithongtin","loaitoipham","ngaycapcccdnguyendon","ngaydexuat","ngaygiaodonvigiaiquyet","ngayphieuchuyen","ngaytiepnhannguontin","ngayvietdon","ngayxayra","nghivandoituong","nguondon","nhanxet","noicapcccdnguyendon","noixayra","noixayraphuongxa","phanloaihosodoi1","phanloaitoiphamcongnghecao","phanloaitoiphamtheolinhvuc","phuongthucthudoan","sinhnamnguoitogiac","socccdnguyendon","sodienthoainguyendon","soluongbihai","sophieuchuyen","sotienbithiethai","tencanhancoquantochuccungcap","thoihanthuchienuythacdieutra","toidanhbandau","tomtatnoidung","truonghopbaocaobangiamdoc","yeucaubosung"],
  incident: ["cancuraquyetdinhkhongkhoito","cancutamdinhchinguontin","dexuat","diachibihai","dieutravien","dieutravienphuongxa","dovattailieukemtheo","ghichukhac","ghichutrungdon","ketquaxulygiaiquyetkhac","lanhdaototung","loaithongtin","ngaycapcccdnguyendon","ngaydexuat","ngaygiaodonvigiaiquyet","ngayphieuchuyen","ngayphuchoinguontintoipham","ngayraquyetdinhphancongtinbao","ngayraquyetdinhtamdinhchinguontin","ngaythangnamhetthoihieuvuviec","ngaytiepnhannguontin","ngayvietdon","nghivandoituong","nguondon","nhanxet","noicapcccdnguyendon","noixayra","phanloaidansu","phanloaihosodoi1","phanloaitoiphamcongnghecao","phanloaitoiphamtheolinhvuc","phuchoinguontintoipham","quyetdinhphanconggiaiquyetnguontin","quyetdinhtamdinhchinguontin","sinhnamnguoitogiac","socccdnguyendon","sodienthoainguyendon","sophieuchuyen","tencanhancoquantochuccungcap","tiendokhacphuctdc","toidanhbandau","tomtatnoidung","truonghopbaocaobangiamdoc","vuviecchuyendonvikhac","yeucaubosung"],
  case: ["batduocbaonhieubangnhom","bihai","cancuphuchoidieutravuan","cancutamdinhchivuan","cccdcungcap","chuyenvuanchocoquankhac","cobaonhieubangnhom","damageamount","description","dexuat","dexuatxuly","diachibihai","diachicungcap","dieutramorong","dieutravien","dieutravientext","dinhchivuan","donvibaoquanhoso","donviuythac","dovattailieukemtheo","ghiamghihinhdaduocxetxu","ghichukhac","ghichunhaphoso","ghichutrungdon","hosoluu","ketluandieutravuan","ketquauythac","ketquaxulygiaiquyetkhac","ketquaxulykhac","lanhdaototung","loaithongtin","motachitiet","ngaybanancohieuluc","ngaycapcccd","ngaycapcccdnguyendon","ngaydangkyhoso","ngaydexuat","ngaygiaodonvigiaiquyet","ngayhetthoihieutruycuutnhsvuan","ngayketluandieutra","ngaynhapvuan","ngaynopluuhoso","ngayphieuchuyen","ngayquyetdinhdieutralai","ngayquyetdinhdinhchivuan","ngayquyetdinhkhoitovuan","ngayquyetdinhtachhanhvi","ngayraquyetdinhkhoito","ngaytachhoso","ngaytamdinhchivuan","ngaytiepnhannguontin","ngaytiepnhanuythac","ngaytraketquauythac","ngayvietdon","nghivandoituong","nguondon","nhanxet","noicapcccd","noicapcccdnguyendon","noixayra","phanloaihosodoi1","phanloaihosonoibo","phanloaitoiphamcongnghecao","phanloaitoiphamlinhvuc","phanloaitoiphamtheolinhvuc","phuongthucthudoan","quyetdinhdieutralai","quyetdinhkhoitovuan","quyetdinhkhongkhoito","quyetdinhnhapvuan","quyetdinhtachhanhvi","quyetdinhtachvuan","quyetdinhtamdinhchivuan","sdtcungcap","sinhnamcungcap","sinhnamnguoitogiac","sobanancohieuluc","socccdnguyendon","sodangkyhoso","sodienthoainguyendon","sodoituong","sodoituongbibattrongvuankhac","sodoituongdabat","soluongbihai","soluongnguoichet","soluongsungthuhoi","soluongthuocnothuhoi","songuoibithuong","sophieuchuyen","soquyetdinhuythac","sotienbithiethai","sotienthuhoi","sttcu","tencanhancoquantochuccungcap","tencungcap","thoihanthuchienuythacdieutra","toidanhbandau","tomtatnoidung","truonghopbaocaobangiamdoc","vuancosudungketquảghiamghihinhtrongxetxu","vuankhonggaghnhungtoaanyeucaucungcapgagh","xacnhanghiamghihinh","xacnhanneulavuanghiamghihinh","xacnhanvuandaduocxetxu","xacnhanvuviecvphc","yeucaubosung"],
};
const MAIN: Record<LegacyEntity, string[]> = {
  petition: ["assignedtoid","attachmentsnote","baocaobangiamdoc","canbodexuatid","crimechinhid","deadline","detailcontent","dexuat","dieutravien","donvigiaiquyet","donvixuly","ketquaxulykhac","lacongnghecao","lanhdaototung","loaithongtin","loaitoipham","ngaydexuat","ngaygiaodonvigiaiquyet","ngayphieuchuyen","ngaytiepnhannguontin","ngayxayra","nguondon","nhanthay","noixayra","noixayraphuongxa","notes","petitiondate","petitiontype","phanloainguontin","phuongthucthudoan","priority","rasoattrung","receiveddate","senderaddress","senderbirthyear","senderemail","senderidissuedate","senderidissueplace","senderidnumber","senderisanonymous","sendername","senderphone","sophieuchuyen","stt","suspectedaddress","suspectedperson","thoihanutdt","thuocthamquyen","toidanhbandau","unit"],
  incident: ["benvu","canbonhapid","cancukhoitocode","cancukhongkhoito","cancutamdinhchi","cmndnguoitogiac","deadline","description","diachinguoitogiac","diachixayra","doituongcanhan","doituongtochuc","donvigiaiquyet","fromdate","investigatorid","ketquaxuly","khacphucbienban","khacphuclydobienphap","lacongnghecaovv","loaidonvu","loaiketqua","lydokhongkhoito","lydotamdinhchi","lydotamdinhchivuviec","name","ngaydexuat","ngayhetthoihieuvv","ngayphuchoivv","ngayqdkhongkhoito","ngayqdphancongnguontin","ngayquyetdinh","ngaytamdinhchivv","nguoiquyetdinh","nguonphattin","phanloaidansutext","phuongthuctiepnhan","sdtnguoitogiac","soqdkhongkhoito","soqdphancongnguontin","soquyetdinh","soquyetdinhphuchoivv","soquyetdinhtamdinhchivv","tiendokhacphuctdc","tinhtranghoso","tinhtrangthoihieu","todate","type","xacdinhvuviectamdung"],
  case: ["accusation","address","bihai","cancuphuchoivuan","cancutamdinhchivuan","capdotoipham","caseclassification","casecode","caseprovenance","casetitle","casetype","cause","cccdcungcap","chuyenvuanchocqk","closeddate","code","content","crimechinhid","crimefield","crimemethod","damageamount","damagedescription","date","dateofbirth","deathcount","description","detentionstatus","dexuatxuly","dieutravientext","district","donvigiao","email","entryorder","evidencecollected","evidencetype","expectedincidentupdatedat","expectedpetitionupdatedat","gender","ghichukhac","ghichunhaphoso","handler","hearingdate","idnumber","incidentcode","incidentdate","incidentdistrict","incidentprovince","incidenttime","incidentward","informanttype","initialclassification","injurycount","investigationdeadline","investigationresult","investigationstartdate","ketquauythac","ketquaxulykhac","khacphucbienban","khacphuclydobienphap","level","linkedincidentid","linkedpetitionid","loaithongtin","loaiuythac","location","lydokhongthuchienduoc","lydotamdinhchivuan","method","name","nationality","ngaybanancohieuluc","ngaydinhchivuan","ngayhetthoihieu","ngaykhoito","ngaykldt","ngaynhapvuan","ngayphuchoi","ngayqddieutralai","ngaytachhanhvi","ngaytachvuan","ngaytamdinhchi","ngaythongbaokhongthuchien","ngaytiepnhan","ngaytraketqua","nghivandoituong","nguondon","nhanxet","noicapcccd","noixayra","note","occupation","organizedcrime","phanloaitoiphamlinhvuc","phone","phuongthucthudoan","primarycrime","priority","processingdays","processingresult","processingstatus","propertydamage","propertyseized","prosecutionoffice","prosecutionofficeassigned","prosecutionresult","province","quantity","receivedate","receiveddate","receivemethod","receivetime","record","recoveredamount","relatedcasecode","relationtocase","repeatoffender","reportingunit","result","sdtcungcap","secondarycrime","secondarytype","sentence","sentencingresult","sinhnamcungcap","sobanancohieuluc","sohosocu","sokldt","sophieuchuyen","soqddieutralai","soqddinhchivuan","soqdnhapvuan","soqdtachhanhvi","soqdtachvuan","soquyetdinhkhoito","soquyetdinhphuchoi","soquyetdinhtamdinhchi","soquyetdinhuythac","source","sourcedocumentnote","sourceorigin","sourcetype","specificaddress","storagelocation","sttcu","supervisingunit","suspectage","suspecteducation","suspectgender","tencungcap","thoihanuythac","time","tinhtrang","toidanhkhacids","transferdate","trialresult","type","unit","urgencylevel","us","verdict","victimcount","ward","warehousereceipt","witnesscount","yeucaubosung"],
};
const norm = (k: string) => k.toLowerCase().replace(/^(utdt|stat|tdc|reporter|incident|criminal|court)/, '').replace(/[_-]/g, '');
const S = (a: string[]) => new Set(a);
const COL_SET: Record<LegacyEntity, Set<string>> = { petition: S(COL.petition), incident: S(COL.incident), case: S(COL.case) };
const MAIN_SET: Record<LegacyEntity, Set<string>> = { petition: S(MAIN.petition), incident: S(MAIN.incident), case: S(MAIN.case) };

/** Key hệ cũ đã có ô nhập (cột typed HOẶC form chính) → ẩn khỏi panel metadata/raw để không lặp. */
export function hasShownInput(entity: LegacyEntity, key: string): boolean {
  const n = norm(key);
  return COL_SET[entity].has(n) || MAIN_SET[entity].has(n);
}
/** Field này form CHÍNH đã render → LegacyParityFields bỏ để không hiện 2 ô. */
export function inMainForm(entity: LegacyEntity, key: string): boolean {
  return MAIN_SET[entity].has(norm(key));
}
