/**
 * reset-cases.ts
 * Xóa toàn bộ data liên quan đến cases (subjects, lawyers, proposals, delegations, conclusions, petitions, incidents)
 * và tạo lại cases mới với metadata đầy đủ
 */

import { PrismaClient, CaseStatus } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as bcrypt from 'bcrypt';

const adapter = new PrismaPg({
  connectionString:
    process.env['DATABASE_URL'] ??
    'postgresql://pc02_admin:pc02_password@localhost:5432/pc02_db?schema=public',
});
const prisma = new PrismaClient({ adapter });

function daysFromNow(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d;
}

function daysAgo(days: number): Date {
  return daysFromNow(-days);
}

function formatDate(d: Date): string {
  return d.toISOString().split('T')[0];
}

async function main() {
  console.log('🗑️  Xóa toàn bộ data cũ...');

  // Xóa theo thứ tự FK dependency
  await prisma.conclusion.deleteMany({});
  console.log('   ✓ conclusions deleted');
  await prisma.delegation.deleteMany({});
  console.log('   ✓ delegations deleted');
  await prisma.proposal.deleteMany({});
  console.log('   ✓ proposals deleted');
  await prisma.lawyer.deleteMany({});
  console.log('   ✓ lawyers deleted');
  await prisma.subject.deleteMany({});
  console.log('   ✓ subjects deleted');
  await prisma.petition.deleteMany({});
  console.log('   ✓ petitions deleted');
  await prisma.incident.deleteMany({});
  console.log('   ✓ incidents deleted');
  await prisma.case.deleteMany({});
  console.log('   ✓ cases deleted');

  console.log('\n📝 Tạo cases mới với metadata đầy đủ...\n');

  // Lấy users
  const users = await prisma.user.findMany({ select: { id: true, firstName: true, lastName: true, username: true } });
  const dtv1 = users.find(u => u.username === 'dtv01')!;
  const dtv2 = users.find(u => u.username === 'dtv02')!;
  const dtv3 = users.find(u => u.username === 'dtv03')!;
  const dtv4 = users.find(u => u.username === 'dtv04')!;
  const dtv5 = users.find(u => u.username === 'dtv05')!;

  if (!dtv1 || !dtv2 || !dtv3 || !dtv4 || !dtv5) {
    throw new Error('Không tìm thấy điều tra viên. Chạy seed.ts trước!');
  }

  // Định nghĩa 15 vụ án với metadata đầy đủ
  const caseDefs = [
    {
      name: 'Vụ trộm cắp xe máy tại chung cư Sunrise City',
      crime: 'Trộm cắp tài sản (Điều 173 BLHS)',
      status: CaseStatus.TIEP_NHAN,
      unit: 'Công an Quận 7',
      investigatorId: dtv1.id,
      deadline: daysFromNow(30),
      metadata: {
        caseCode: 'HS-2026-001',
        receiveDate: formatDate(daysAgo(2)),
        receiveTime: '08:30',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'trung-binh',
        description: 'Bị hại báo bị mất 1 xe máy Honda Vision BKS 59G1-12345 tại bãi giữ xe chung cư. Camera ghi hình nghi phạm là nam thanh niên khoảng 25 tuổi.',
        investigationStartDate: formatDate(daysAgo(1)),
        prosecutionOfficeAssigned: 'vks-quan-7',
        damageAmount: '35000000',
        damageDescription: '1 xe máy Honda Vision đăng ký chính chủ, mới mua được 6 tháng',
        note: 'Cần phối hợp với CA phường để trích xuất camera an ninh',
        reporter: 'Nguyễn Văn An',
        reporterIdNumber: '079201001234',
        reporterDateOfBirth: '1990-05-15',
        reporterGender: 'NAM',
        reporterPhone: '0901234567',
        reporterEmail: 'an.nguyen@email.com',
        reporterAddress: '123 Nguyễn Lương Bằng, Phường Tân Phú, Quận 7',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Nhân viên văn phòng',
        reporterRelationToCase: 'BI_HAI',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 7',
        ward: 'Phường Tân Phú',
        specificAddress: 'Chung cư Sunrise City, 23 Nguyễn Lương Bằng',
      },
    },
    {
      name: 'Vụ lừa đảo đầu tư tài chính qua mạng',
      crime: 'Lừa đảo chiếm đoạt tài sản (Điều 174 BLHS)',
      status: CaseStatus.TIEP_NHAN,
      unit: 'Công an Quận 1',
      investigatorId: dtv2.id,
      deadline: daysFromNow(45),
      metadata: {
        caseCode: 'HS-2026-002',
        receiveDate: formatDate(daysAgo(3)),
        receiveTime: '14:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Bị hại bị lừa đảo đầu tư vào sàn Forex giả, mất tổng cộng 2 tỷ đồng. Đối tượng sử dụng website giả mạo và nhóm Zalo để thao túng nạn nhân.',
        prosecutionOfficeAssigned: 'vks-quan-1',
        damageAmount: '2000000000',
        damageDescription: 'Tiền chuyển khoản qua 5 tài khoản ngân hàng khác nhau trong vòng 2 tháng',
        note: 'Cần phối hợp với Cục Cảnh sát điều tra tội phạm về công nghệ cao (C50)',
        reporter: 'Trần Thị Bình',
        reporterIdNumber: '079198505678',
        reporterDateOfBirth: '1985-08-20',
        reporterGender: 'NU',
        reporterPhone: '0912345678',
        reporterEmail: 'binh.tran@email.com',
        reporterAddress: '45 Lê Lợi, Phường Bến Nghé, Quận 1',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Kinh doanh tự do',
        reporterRelationToCase: 'BI_HAI',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 1',
        ward: 'Phường Bến Nghé',
        specificAddress: '45 Lê Lợi, Phường Bến Nghé, Quận 1',
      },
    },
    {
      name: 'Vụ tàng trữ trái phép chất ma túy tại phường Tây Thạnh',
      crime: 'Tàng trữ trái phép chất ma túy (Điều 193 BLHS)',
      status: CaseStatus.DANG_XAC_MINH,
      unit: 'Công an Quận Tân Bình',
      investigatorId: dtv3.id,
      deadline: daysFromNow(20),
      metadata: {
        caseCode: 'HS-2026-003',
        receiveDate: formatDate(daysAgo(5)),
        receiveTime: '22:45',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Tổ công tác CA phường Tây Thạnh phát hiện đối tượng Lê Văn Dũng (SN 1990) tàng trữ 0.5 gram heroin tại nhà riêng. Đối tượng đã bị bắt giữ.',
        investigationStartDate: formatDate(daysAgo(5)),
        prosecutionOfficeAssigned: 'vks-quan-tan-binh',
        damageAmount: '0',
        damageDescription: 'Không có thiệt hại tài sản',
        note: 'Đối tượng có tiền án về tội trộm cắp. Cần mở rộng điều tra nguồn cung cấp ma túy.',
        reporter: 'Tổ công tác CA Phường Tây Thạnh',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: '',
        reporterPhone: '',
        reporterEmail: '',
        reporterAddress: '',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Cán bộ công an',
        reporterRelationToCase: 'CO_QUAN_TO_CHUC',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận Tân Bình',
        ward: 'Phường Tây Thạnh',
        specificAddress: 'Khu phố 5, Phường Tây Thạnh, Quận Tân Bình',
      },
    },
    {
      name: 'Vụ cướp giật điện thoại khu vực Bến Thành',
      crime: 'Cướp tài sản (Điều 168 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an Quận 1',
      investigatorId: dtv1.id,
      deadline: daysFromNow(10),
      metadata: {
        caseCode: 'HS-2026-004',
        receiveDate: formatDate(daysAgo(10)),
        receiveTime: '19:30',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Bị hại bị 2 đối tượng đi xe máy cướp giật điện thoại iPhone 15 Pro Max khi đang đi bộ tại khu vực chợ Bến Thành. Camera an ninh đã ghi hình rõ mặt 2 đối tượng.',
        investigationStartDate: formatDate(daysAgo(9)),
        prosecutionOfficeAssigned: 'vks-quan-1',
        damageAmount: '28000000',
        damageDescription: '1 điện thoại iPhone 15 Pro Max 256GB, mới mua được 1 tháng',
        note: 'Đối tượng nghi vấn đã được nhận dạng, đang tiến hành bắt giữ',
        reporter: 'Phạm Thị Cúc',
        reporterIdNumber: '079199507890',
        reporterDateOfBirth: '1995-03-10',
        reporterGender: 'NU',
        reporterPhone: '0987654321',
        reporterEmail: 'cuc.pham@email.com',
        reporterAddress: '78 Trần Hưng Đạo, Phường Cầu Ông Lãnh, Quận 1',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Nhân viên marketing',
        reporterRelationToCase: 'BI_HAI',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 1',
        ward: 'Phường Bến Thành',
        specificAddress: 'Khu vực chợ Bến Thành, đường Lê Lợi',
      },
    },
    {
      name: 'Vụ án ma túy đường dây liên tỉnh',
      crime: 'Vận chuyển trái phép chất ma túy (Điều 194 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an TP. Hồ Chí Minh',
      investigatorId: dtv1.id,
      deadline: daysFromNow(60),
      metadata: {
        caseCode: 'HS-2026-005',
        receiveDate: formatDate(daysAgo(15)),
        receiveTime: '03:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'khan-cap',
        description: 'Phá đường dây ma túy liên tỉnh từ Campuchia về TP.HCM. Thu giữ 5kg heroin, 2000 viên ma túy tổng hợp. 4 đối tượng đã bị bắt giữ.',
        investigationStartDate: formatDate(daysAgo(15)),
        prosecutionOfficeAssigned: 'vks-tphcm',
        damageAmount: '0',
        damageDescription: 'Không có thiệt hại tài sản. Số lượng ma túy thu giữ rất lớn.',
        note: 'Vụ án đặc biệt nghiêm trọng, báo cáo Lãnh đạo Bộ Công an. Cần phối hợp với CA tỉnh Bình Dương, Long An.',
        reporter: 'Phòng PC04 - CATP',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: '',
        reporterPhone: '',
        reporterEmail: '',
        reporterAddress: '',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Cơ quan công an',
        reporterRelationToCase: 'CO_QUAN_TO_CHUC',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 1',
        ward: 'Phường Bến Nghé',
        specificAddress: 'Khu vực cửa khẩu Mộc Bài - Tây Ninh (điểm xuất phát)',
      },
    },
    {
      name: 'Vụ lừa đảo chiếm đoạt đất đai Huyện Củ Chi',
      crime: 'Lừa đảo chiếm đoạt tài sản (Điều 174 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an Huyện Củ Chi',
      investigatorId: dtv2.id,
      deadline: daysFromNow(40),
      metadata: {
        caseCode: 'HS-2026-006',
        receiveDate: formatDate(daysAgo(20)),
        receiveTime: '09:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Đối tượng伪造 giấy tờ đất đai, lừa đảo bán đất cho 5 nạn nhân với tổng số tiền 5 tỷ đồng. Đất thực tế thuộc sở hữu của người khác.',
        investigationStartDate: formatDate(daysAgo(18)),
        prosecutionOfficeAssigned: 'vks-tphcm',
        damageAmount: '5000000000',
        damageDescription: '5 bị hại bị lừa đảo chiếm đoạt đất đai, tổng diện tích 5000m2',
        note: 'Cần phối hợp với Văn phòng đăng ký đất đai để xác minh giấy tờ',
        reporter: 'Hoàng Văn Đức',
        reporterIdNumber: '079197003456',
        reporterDateOfBirth: '1970-11-25',
        reporterGender: 'NAM',
        reporterPhone: '0909123456',
        reporterEmail: 'duc.hoang@email.com',
        reporterAddress: 'Thị trấn Củ Chi, Huyện Củ Chi',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Nông dân',
        reporterRelationToCase: 'BI_HAI',
        province: 'TP. Hồ Chí Minh',
        district: 'Huyện Củ Chi',
        ward: 'Xã Phú Mỹ Hưng',
        specificAddress: 'Ấp 1, Xã Phú Mỹ Hưng, Huyện Củ Chi',
      },
    },
    {
      name: 'Vụ cố ý gây thương tích tại quán nhậu đường Bùi Viện',
      crime: 'Cố ý gây thương tích (Điều 134 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an Quận 1',
      investigatorId: dtv3.id,
      deadline: daysFromNow(35),
      metadata: {
        caseCode: 'HS-2026-007',
        receiveDate: formatDate(daysAgo(7)),
        receiveTime: '23:45',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Xô xát tại quán nhậu trên đường Bùi Viện, bị can dùng chai bia đánh bị hại gây thương tích 15% cơ thể. Bị can đã bị bắt giữ.',
        investigationStartDate: formatDate(daysAgo(6)),
        prosecutionOfficeAssigned: 'vks-quan-1',
        damageAmount: '50000000',
        damageDescription: 'Chi phí y tế ban đầu 50 triệu đồng, tỷ lệ thương tật 15%',
        note: 'Bị can có tiền sử nghiện rượu, cần giám định tâm thần',
        reporter: 'Quán nhậu Bùi Viện Night',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: '',
        reporterPhone: '02838223456',
        reporterEmail: '',
        reporterAddress: '123 Bùi Viện, Phường Phạm Ngũ Lão, Quận 1',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Cơ sở kinh doanh',
        reporterRelationToCase: 'NHAN_CHUNG',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 1',
        ward: 'Phường Phạm Ngũ Lão',
        specificAddress: '123 Đường Bùi Viện, Phường Phạm Ngũ Lão, Quận 1',
      },
    },
    {
      name: 'Vụ giết người mâu thuẫn gia đình phường Võ Thị Sáu',
      crime: 'Giết người (Điều 123 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an Quận 3',
      investigatorId: dtv5.id,
      deadline: daysFromNow(90),
      metadata: {
        caseCode: 'HS-2026-008',
        receiveDate: formatDate(daysAgo(12)),
        receiveTime: '06:30',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'khan-cap',
        description: 'Bị can Võ Văn Bình dùng dao giết vợ là Võ Thị Cẩm Vân tại nhà riêng. Nghi ngờ do mâu thuẫn gia đình kéo dài. Bị can đã đầu thú.',
        investigationStartDate: formatDate(daysAgo(12)),
        prosecutionOfficeAssigned: 'vks-quan-3',
        damageAmount: '0',
        damageDescription: 'Nạn nhân tử vong tại chỗ',
        note: 'Vụ án đặc biệt nghiêm trọng. Cần giám định tâm thần bị can. Báo cáo Lãnh đạo Phòng.',
        reporter: 'Võ Văn Bình',
        reporterIdNumber: '079197505678',
        reporterDateOfBirth: '1975-08-15',
        reporterGender: 'NAM',
        reporterPhone: '0908765432',
        reporterEmail: '',
        reporterAddress: '22 Nguyễn Đình Chiểu, Phường Võ Thị Sáu, Quận 3',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Lao động tự do',
        reporterRelationToCase: 'BI_CAN',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 3',
        ward: 'Phường Võ Thị Sáu',
        specificAddress: '22 Nguyễn Đình Chiểu, Phường Võ Thị Sáu, Quận 3',
      },
    },
    {
      name: 'Vụ trộm cắp tài sản siêu thị Coopmart - Đã kết luận',
      crime: 'Trộm cắp tài sản (Điều 173 BLHS)',
      status: CaseStatus.DA_KET_LUAN,
      unit: 'Công an Quận 10',
      investigatorId: dtv5.id,
      deadline: daysAgo(30),
      metadata: {
        caseCode: 'HS-2026-009',
        receiveDate: formatDate(daysAgo(90)),
        receiveTime: '15:20',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'trung-binh',
        description: 'Bị can trộm hàng hóa trị giá 15 triệu đồng tại siêu thị Coopmart. Camera ghi hình rõ ràng. Bị can đã thú nhận và trả lại hàng.',
        investigationStartDate: formatDate(daysAgo(88)),
        prosecutionOfficeAssigned: 'vks-quan-10',
        damageAmount: '15000000',
        damageDescription: 'Hàng hóa tiêu dùng các loại, đã được thu hồi',
        note: 'Bị can là sinh viên lần đầu phạm tội, có tình tiết giảm nhẹ. Đã chuyển hồ sơ sang VKS để truy tố.',
        reporter: 'Bảo vệ siêu thị Coopmart',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: 'NAM',
        reporterPhone: '02838601234',
        reporterEmail: '',
        reporterAddress: '300 Lý Thường Kiệt, Quận 10',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Nhân viên bảo vệ',
        reporterRelationToCase: 'NHAN_CHUNG',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 10',
        ward: 'Phường 14',
        specificAddress: 'Siêu thị Coopmart, 300 Lý Thường Kiệt, Quận 10',
      },
    },
    {
      name: 'Vụ ma túy cá nhân sử dụng - Đình chỉ điều tra',
      crime: 'Tàng trữ trái phép chất ma túy (Điều 193 BLHS)',
      status: CaseStatus.DINH_CHI,
      unit: 'Công an Quận Tân Bình',
      investigatorId: dtv1.id,
      deadline: daysAgo(15),
      metadata: {
        caseCode: 'HS-2026-010',
        receiveDate: formatDate(daysAgo(60)),
        receiveTime: '21:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'thap',
        description: 'Đối tượng tàng trữ 0.1 gram ma túy cho mục đích sử dụng cá nhân. Sau khi giám định, đối tượng là người nghiện ma túy.',
        investigationStartDate: formatDate(daysAgo(58)),
        prosecutionOfficeAssigned: 'vks-quan-tan-binh',
        damageAmount: '0',
        damageDescription: 'Không có thiệt hại tài sản',
        note: 'Đình chỉ điều tra theo quy định tại Điều 29 BLTTHS. Đối tượng được đưa vào cơ sở cai nghiện bắt buộc.',
        reporter: 'CA Phường Phú Thạnh',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: '',
        reporterPhone: '',
        reporterEmail: '',
        reporterAddress: '',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Cơ quan công an',
        reporterRelationToCase: 'CO_QUAN_TO_CHUC',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận Tân Bình',
        ward: 'Phường Phú Thạnh',
        specificAddress: 'Khu phố 3, Phường Phú Thạnh, Quận Tân Bình',
      },
    },
    {
      name: 'Vụ trộm cắp tài sản trong nhà trọ (QUÁ HẠN)',
      crime: 'Trộm cắp tài sản (Điều 173 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an Huyện Hóc Môn',
      investigatorId: dtv3.id,
      deadline: daysAgo(5),
      metadata: {
        caseCode: 'HS-2026-011',
        receiveDate: formatDate(daysAgo(35)),
        receiveTime: '07:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Trộm laptop và tiền mặt tại phòng trọ. Nghi phạm là người thuê phòng kế bên đã bỏ trốn.',
        investigationStartDate: formatDate(daysAgo(33)),
        prosecutionOfficeAssigned: 'vks-tphcm',
        damageAmount: '25000000',
        damageDescription: '1 laptop MacBook Pro, tiền mặt 10 triệu đồng',
        note: 'Vụ án đã quá hạn điều tra. Cần khẩn trương truy tìm nghi phạm.',
        reporter: 'Nguyễn Thị Hồng',
        reporterIdNumber: '079199201234',
        reporterDateOfBirth: '1992-06-18',
        reporterGender: 'NU',
        reporterPhone: '0933123456',
        reporterEmail: 'hong.nguyen@email.com',
        reporterAddress: 'Phòng trọ số 5, khu phố 2, Huyện Hóc Môn',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Nhân viên văn phòng',
        reporterRelationToCase: 'BI_HAI',
        province: 'TP. Hồ Chí Minh',
        district: 'Huyện Hóc Môn',
        ward: 'Xã Xuân Thới Sơn',
        specificAddress: 'Khu phố 2, Ấp 3, Xã Xuân Thới Sơn, Huyện Hóc Môn',
      },
    },
    {
      name: 'Vụ cưỡng đoạt tài sản học sinh (QUÁ HẠN)',
      crime: 'Cưỡng đoạt tài sản (Điều 170 BLHS)',
      status: CaseStatus.DANG_XAC_MINH,
      unit: 'Công an Quận Phú Nhuận',
      investigatorId: dtv4.id,
      deadline: daysAgo(10),
      metadata: {
        caseCode: 'HS-2026-012',
        receiveDate: formatDate(daysAgo(40)),
        receiveTime: '16:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Nhóm học sinh ép bạn cùng lớp nộp tiền mỗi tuần. Tổng số tiền 5 triệu đồng trong 2 tháng.',
        investigationStartDate: formatDate(daysAgo(35)),
        prosecutionOfficeAssigned: 'vks-quan-phu-nhuan',
        damageAmount: '5000000',
        damageDescription: 'Tiền mặt bị cưỡng đoạt trong 2 tháng',
        note: 'Vụ án liên quan đến người chưa thành niên. Cần phối hợp với nhà trường và gia đình.',
        reporter: 'Phụ huynh học sinh',
        reporterIdNumber: '079198507890',
        reporterDateOfBirth: '1985-12-05',
        reporterGender: 'NAM',
        reporterPhone: '0918123456',
        reporterEmail: 'phuhuynh@email.com',
        reporterAddress: '45 Hoàng Văn Thụ, Quận Phú Nhuận',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Kinh doanh',
        reporterRelationToCase: 'NGUOI_BAO_TIN',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận Phú Nhuận',
        ward: 'Phường 15',
        specificAddress: 'Trường THCS XYZ, 45 Hoàng Văn Thụ, Quận Phú Nhuận',
      },
    },
    {
      name: 'Vụ tai nạn giao thông chết người đường Lê Văn Sỹ',
      crime: 'Vi phạm quy định về tham gia GTĐB (Điều 260 BLHS)',
      status: CaseStatus.DANG_DIEU_TRA,
      unit: 'Công an Quận 3',
      investigatorId: dtv5.id,
      deadline: daysFromNow(15),
      metadata: {
        caseCode: 'HS-2026-013',
        receiveDate: formatDate(daysAgo(8)),
        receiveTime: '02:30',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'cao',
        description: 'Xe máy chạy tốc độ cao tông vào dải phân cách trên đường Lê Văn Sỹ, tài xế tử vong. Nghi ngờ tài xế có sử dụng rượu bia.',
        investigationStartDate: formatDate(daysAgo(7)),
        prosecutionOfficeAssigned: 'vks-quan-3',
        damageAmount: '50000000',
        damageDescription: 'Chi phí tang lễ cho gia đình nạn nhân',
        note: 'Chờ kết quả giám định nồng độ cồn. Nạn nhân là người duy nhất trên xe.',
        reporter: 'Cảnh sát giao thông Quận 3',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: '',
        reporterPhone: '',
        reporterEmail: '',
        reporterAddress: '',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Cơ quan công an',
        reporterRelationToCase: 'CO_QUAN_TO_CHUC',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 3',
        ward: 'Phường 14',
        specificAddress: 'Đường Lê Văn Sỹ, đoạn gần ngã tư Cộng Hòa',
      },
    },
    {
      name: 'Vụ trộm cắp xe đạp điện tại trường học',
      crime: 'Trộm cắp tài sản (Điều 173 BLHS)',
      status: CaseStatus.DA_XAC_MINH,
      unit: 'Công an Quận 5',
      investigatorId: dtv1.id,
      deadline: daysFromNow(20),
      metadata: {
        caseCode: 'HS-2026-014',
        receiveDate: formatDate(daysAgo(15)),
        receiveTime: '11:30',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'trung-binh',
        description: 'Trộm xe đạp điện tại bãi xe trường học. Camera ghi hình nghi phạm là học sinh trường khác.',
        investigationStartDate: formatDate(daysAgo(14)),
        prosecutionOfficeAssigned: 'vks-quan-5',
        damageAmount: '12000000',
        damageDescription: '1 xe đạp điện VinFast, mới mua được 3 tháng',
        note: 'Đối tượng là người chưa thành niên, cần phối hợp với gia đình và nhà trường.',
        reporter: 'Bảo vệ trường học',
        reporterIdNumber: '',
        reporterDateOfBirth: '',
        reporterGender: 'NAM',
        reporterPhone: '02838345678',
        reporterEmail: '',
        reporterAddress: '123 Hùng Vương, Quận 5',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Nhân viên bảo vệ',
        reporterRelationToCase: 'NHAN_CHUNG',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận 5',
        ward: 'Phường 11',
        specificAddress: 'Trường THPT XYZ, 123 Hùng Vương, Quận 5',
      },
    },
    {
      name: 'Vụ lừa đảo bán hàng online giả mạo',
      crime: 'Lừa đảo chiếm đoạt tài sản (Điều 174 BLHS)',
      status: CaseStatus.DA_XAC_MINH,
      unit: 'Công an Quận Bình Thạnh',
      investigatorId: dtv2.id,
      deadline: daysFromNow(28),
      metadata: {
        caseCode: 'HS-2026-015',
        receiveDate: formatDate(daysAgo(20)),
        receiveTime: '10:00',
        caseType: 'vu-an',
        caseClassification: 'hinh-su',
        priority: 'trung-binh',
        description: 'Lập website bán hàng online giả mạo thương hiệu lớn, lừa đảo 50 khách hàng với tổng số tiền 300 triệu đồng.',
        investigationStartDate: formatDate(daysAgo(18)),
        prosecutionOfficeAssigned: 'vks-quan-binh-thanh',
        damageAmount: '300000000',
        damageDescription: 'Tiền của 50 khách hàng bị lừa đảo khi đặt hàng online',
        note: 'Cần phối hợp với C50 để truy vết website và tài khoản ngân hàng',
        reporter: 'Nguyễn Văn Khách',
        reporterIdNumber: '079199101234',
        reporterDateOfBirth: '1991-04-20',
        reporterGender: 'NAM',
        reporterPhone: '0933456789',
        reporterEmail: 'khach.nguyen@email.com',
        reporterAddress: '78 Xô Viết Nghệ Tĩnh, Quận Bình Thạnh',
        reporterNationality: 'Việt Nam',
        reporterOccupation: 'Kỹ sư IT',
        reporterRelationToCase: 'BI_HAI',
        province: 'TP. Hồ Chí Minh',
        district: 'Quận Bình Thạnh',
        ward: 'Phường 25',
        specificAddress: 'Website: www.fake-shop.com (đã bị khóa)',
      },
    },
  ];

  // Tạo cases
  let createdCount = 0;
  for (const def of caseDefs) {
    const c = await prisma.case.create({
      data: {
        name: def.name,
        crime: def.crime,
        status: def.status,
        unit: def.unit,
        investigatorId: def.investigatorId,
        deadline: def.deadline,
        subjectsCount: 0,
        metadata: def.metadata,
      },
    });
    createdCount++;
    console.log(`   ✓ ${createdCount}. ${def.name}`);
  }

  console.log(`\n✅ Hoàn tất! Đã tạo ${createdCount} vụ án với metadata đầy đủ.`);
  console.log('\n📊 Thống kê:');
  const statusCount = await prisma.case.groupBy({
    by: ['status'],
    _count: true,
  });
  statusCount.forEach(s => console.log(`   ${s.status}: ${s._count} vụ`));
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
