// Quản lý Vụ án (Cases) — E2E UI layer (Layer 2)
// Auto-generated by gen_uat_specs.py
import { test, expect } from '@playwright/test';

test.describe('UAT E2E — Quản lý Vụ án (Cases)', () => {
  test.beforeEach(async ({ page }) => {
    // Login skeleton — adapt cho project khi expand
    // await page.goto('/login');
  });


  test('TC-001-E2E: Tạo vụ án mới hợp lệ với provenance DIRECT_DISCOVERY [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-002-E2E: Tạo vụ án từ Petition (FROM_PETITION) với optimistic lock [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-003-E2E: Tạo vụ án từ Incident (FROM_INCIDENT) [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-004-E2E: Tạo vụ án UTDT với caseType=UY_THAC_DIEU_TRA và donViGiao [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-005-E2E: Liệt kê vụ án với pagination mặc định [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-006-E2E: Filter theo status=DANG_DIEU_TRA [@GREEN @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-007-E2E: Search theo tên vụ án (ILIKE) [@GREEN @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-008-E2E: Cập nhật vụ án với optimistic lock đúng [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-009-E2E: Chuyển status TIEP_NHAN → DANG_DIEU_TRA [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-010-E2E: Đặt status TAM_DINH_CHI có lyDoTamDinhChiVuAn [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-011-E2E: Soft-delete vụ án TIEP_NHAN bởi creator với reason [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Delete
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-012-E2E: ADMIN restore vụ án đã xóa [@GREEN @P0]', async ({ page }) => {
    // Module: Cases.Restore
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-013-E2E: Dispatcher gán investigator cho vụ án [@GREEN @P1]', async ({ page }) => {
    // Module: Cases.Assign
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-014-E2E: Export Excel theo phường [@GREEN @P1]', async ({ page }) => {
    // Module: Cases.Export
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-015-E2E: Bulk delete 5 vụ án [@GREEN @P1]', async ({ page }) => {
    // Module: Cases.Bulk
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-016-E2E: Xem journey timeline của vụ án [@GREEN @P1]', async ({ page }) => {
    // Module: Cases.Journey
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-017-E2E: GET /cases/stats trả về count đúng theo status [@GREEN @P2]', async ({ page }) => {
    // Module: Cases.Stats
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-018-E2E: Tạo case kèm 3 subjects + 2 evidences atomic [@GREEN @P2]', async ({ page }) => {
    // Module: Cases.Atomic
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-019-E2E: Tạo vụ án thiếu name (required) [@RED @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-020-E2E: Tạo vụ án không có caseProvenance [@RED @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-021-E2E: FROM_PETITION nhưng thiếu linkedPetitionId [@RED @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-022-E2E: FROM_INCIDENT thiếu linkedIncidentId [@RED @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-023-E2E: UY_THAC_DIEU_TRA thiếu donViGiao (v0.67.3.0) [@RED @P0]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-024-E2E: Optimistic lock conflict khi 2 user edit [@RED @P0]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-025-E2E: Đổi status sang TAM_DINH_CHI thiếu lyDoTamDinhChiVuAn [@RED @P0]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-026-E2E: Non-creator non-admin xóa vụ án [@RED @P0]', async ({ page }) => {
    // Module: Cases.Delete
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-027-E2E: Xóa vụ án không phải TIEP_NHAN [@RED @P0]', async ({ page }) => {
    // Module: Cases.Delete
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-028-E2E: Xóa vụ án còn linked Petition/Incident [@RED @P0]', async ({ page }) => {
    // Module: Cases.Delete
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-029-E2E: Reason xóa <10 ký tự [@RED @P0]', async ({ page }) => {
    // Module: Cases.Delete
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-030-E2E: Non-ADMIN restore [@RED @P0]', async ({ page }) => {
    // Module: Cases.Restore
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-031-E2E: Non-dispatcher gọi assign [@RED @P0]', async ({ page }) => {
    // Module: Cases.Assign
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-032-E2E: User ĐTV scope khác xem case không thuộc tổ [@RED @P0]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-033-E2E: limit > 100 [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-034-E2E: offset âm [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-035-E2E: fromDate > toDate [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-036-E2E: Update tên >500 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-037-E2E: Crime > 255 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-038-E2E: sourceDocumentNote > 1000 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-039-E2E: Subjects > 100 [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-040-E2E: Evidences > 100 [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-041-E2E: documentIds > 50 [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-042-E2E: investigatorId không tồn tại [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-043-E2E: assignedTeamId thuộc đơn vị khác [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-044-E2E: deadline trong quá khứ [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-045-E2E: ngayKhoiTo định dạng sai [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-046-E2E: capDoToiPham không hợp lệ [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-047-E2E: loaiUyThac không thuộc enum [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-048-E2E: Truy cập không JWT [@RED @P0]', async ({ page }) => {
    // Module: Cases.Auth
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-049-E2E: JWT hết hạn [@RED @P0]', async ({ page }) => {
    // Module: Cases.Auth
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-050-E2E: JWT chữ ký sai [@RED @P0]', async ({ page }) => {
    // Module: Cases.Auth
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-051-E2E: Pre-migration createdById=NULL chỉ ADMIN xóa [@RED @P0]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-052-E2E: sortBy với cột không tồn tại [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-053-E2E: trangThaiPhanHoi không hợp lệ [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-054-E2E: Update vụ án đã soft-delete [@RED @P1]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-055-E2E: Bulk assign với ids khác đơn vị [@RED @P1]', async ({ page }) => {
    // Module: Cases.Bulk
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-056-E2E: Bulk delete > 100 items [@RED @P1]', async ({ page }) => {
    // Module: Cases.Bulk
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-057-E2E: Export vượt rate limit 5/min [@RED @P1]', async ({ page }) => {
    // Module: Cases.Export
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-058-E2E: linkedPetitionId thuộc Petition đã linked case khác [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-059-E2E: linkedIncidentId đã được dùng (@unique) [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-060-E2E: Đổi caseProvenance sau khi tạo [@RED @P1]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-061-E2E: name = 500 ký tự (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-062-E2E: name = 499 ký tự (max-1) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-063-E2E: name = 1 ký tự (min) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-064-E2E: limit=100 (max) [@BOUNDARY @P0]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-065-E2E: limit=1 (min) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-066-E2E: reason xóa = 10 ký tự (min) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-067-E2E: reason xóa = 500 ký tự (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-068-E2E: subjects = 100 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-069-E2E: evidences = 100 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-070-E2E: offset=0 (min) [@BOUNDARY @P2]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-071-E2E: caseProvenance hợp lệ — partition cho mỗi giá trị 8 enum [@EP @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-072-E2E: status enum 10 giá trị filter ra đúng partition [@EP @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-073-E2E: capDoToiPham 4 partition [@EP @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-074-E2E: sortOrder asc / desc [@EP @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-075-E2E: overdue=true vs false [@EP @P2]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-076-E2E: DANG_DIEU_TRA → DA_KET_LUAN [@STATE @P0]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-077-E2E: DA_KET_LUAN → DANG_TRUY_TO [@STATE @P0]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-078-E2E: DANG_TRUY_TO → DANG_XET_XU [@STATE @P0]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-079-E2E: TAM_DINH_CHI → DA_KET_LUAN (phục hồi) [@STATE @P0]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-080-E2E: DINH_CHI là terminal [@STATE @P0]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-081-E2E: soLanTamDinhChi auto-increment khi vào TĐC lần 2 [@STATE @P1]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-082-E2E: DA_LUU_TRU không cho edit field nghiệp vụ [@STATE @P2]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-083-E2E: CaseStatusHistory ghi cả from + to + changedBy [@STATE @P1]', async ({ page }) => {
    // Module: Cases.State
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-084-E2E: Decision Table — trangThaiPhanHoi 4 case [@DECISION @P0]', async ({ page }) => {
    // Module: Cases.UTDT
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-085-E2E: Decision Table — lyDoTamDinhChiVuAn cần khi status=TAM_DINH_CHI [@DECISION @P0]', async ({ page }) => {
    // Module: Cases.TDC
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-086-E2E: SQL Injection trong search [@SECURITY @P0]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-087-E2E: XSS trong name vụ án [@SECURITY @P0]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-088-E2E: IDOR — đoán id case khác đơn vị [@SECURITY @P0]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-089-E2E: Mass assignment — gửi createdById trong body [@SECURITY @P0]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-090-E2E: CSRF — POST không token [@SECURITY @P0]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-091-E2E: Path traversal trong filename export [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-092-E2E: NoSQL/Prisma injection trong sortBy [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-093-E2E: Rate limit brute force list endpoint [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-094-E2E: Auth missing trên restore admin endpoint [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-095-E2E: Sensitive data exposure trong audit log API [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-096-E2E: CORS — origin trái phép bị reject [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-097-E2E: JWT replay sau logout [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-098-E2E: Tên vụ án Unicode đa byte (tiếng Việt + emoji) [@DATA @P1]', async ({ page }) => {
    // Module: Cases.Data
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-099-E2E: Trim leading/trailing space [@DATA @P1]', async ({ page }) => {
    // Module: Cases.Data
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-100-E2E: Null byte injection [@DATA @P1]', async ({ page }) => {
    // Module: Cases.Data
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-101-E2E: Date ISO8601 timezone VN (UTC+7) [@DATA @P2]', async ({ page }) => {
    // Module: Cases.Data
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-102-E2E: Number overflow soLanTamDinhChi [@DATA @P2]', async ({ page }) => {
    // Module: Cases.Data
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-103-E2E: Tạo 2 case song song cùng linkedIncidentId [@EDGE @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-104-E2E: Subjects/Evidences trùng code trong 1 case [@EDGE @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-105-E2E: Stats khi DB rỗng (0 case) [@EDGE @P2]', async ({ page }) => {
    // Module: Cases.Stats
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-106-E2E: Tab key di chuyển focus qua mọi field form [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-107-E2E: Label gắn đúng với input (htmlFor) [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-108-E2E: Contrast badge status ≥ 4.5:1 [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-109-E2E: Error message announce qua aria-live [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-110-E2E: Skip link đến nội dung chính [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-111-E2E: Chrome 130+ Windows [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-112-E2E: Firefox 130+ macOS [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-113-E2E: Edge 130+ [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-114-E2E: Safari 17+ [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-115-E2E: Mobile portrait 375x667 (iPhone SE) [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-116-E2E: Tablet 768x1024 [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-117-E2E: GET /cases list 1000 record < 2s [@PERFORMANCE @P0]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-118-E2E: POST tạo case kèm 100 subjects + 100 evidences < 5s [@PERFORMANCE @P1]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-119-E2E: 50 concurrent GET /cases/stats không sập [@PERFORMANCE @P1]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-120-E2E: Export 5000 case không OOM [@PERFORMANCE @P2]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-121-E2E: Tạo case assigned → SSE/push tới investigator [@INTEGRATION @P0]', async ({ page }) => {
    // Module: Cases.Notify
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-122-E2E: Generate caseCode auto khi tạo [@INTEGRATION @P1]', async ({ page }) => {
    // Module: Cases.Doc
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-123-E2E: Tạo case với metadata vượt 64KB JSON [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-124-E2E: caseProvenance=FROM_PETITION với linkedPetitionId không tồn tại [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-125-E2E: linkedPetitionId thuộc Petition đã soft-delete [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-126-E2E: linkedIncidentId thuộc Incident đã soft-delete [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-127-E2E: Update của user khác đơn vị [@RED @P1]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-128-E2E: Stats vụ án không trong scope [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-129-E2E: Subject thiếu fullName trong atomic create [@RED @P1]', async ({ page }) => {
    // Module: Cases.Atomic
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-130-E2E: Evidence thiếu code [@RED @P1]', async ({ page }) => {
    // Module: Cases.Atomic
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-131-E2E: documentIds chứa id không tồn tại [@RED @P1]', async ({ page }) => {
    // Module: Cases.Atomic
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-132-E2E: TĐC backfill bởi non-creator non-admin [@RED @P1]', async ({ page }) => {
    // Module: Cases.Update
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-133-E2E: Journey với page=-1 [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-134-E2E: limit journey > 200 [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-135-E2E: sourceDocumentNote điền khi caseProvenance=FROM_PETITION [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-136-E2E: Bulk export với ids rỗng [@RED @P1]', async ({ page }) => {
    // Module: Cases.Bulk
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-137-E2E: ngayTraKetQua < ngayTiepNhan [@RED @P1]', async ({ page }) => {
    // Module: Cases.UTDT
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-138-E2E: XXE trong upload XML metadata [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-139-E2E: SSRF qua URL field trong notes [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-140-E2E: Privilege escalation — đổi role qua body [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-141-E2E: HTTP method tampering DELETE qua POST _method [@SECURITY @P1]', async ({ page }) => {
    // Module: Cases.Security
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-142-E2E: Form error message screen reader đọc được [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-143-E2E: Keyboard ESC đóng dialog confirm delete [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-144-E2E: Icon-only button có aria-label [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-145-E2E: Pagination total > tổng thật do scope leak [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-146-E2E: Search SQL keyword reserved [@RED @P1]', async ({ page }) => {
    // Module: Cases.Read
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-147-E2E: loaiThongTin > 200 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Cases.Create
    await page.goto('/cases', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });

});