// Quản lý Đơn thư (Petitions) — E2E UI layer (Layer 2)
// Auto-generated by gen_uat_specs.py
import { test, expect } from '@playwright/test';

test.describe('UAT E2E — Quản lý Đơn thư (Petitions)', () => {
  test.beforeEach(async ({ page }) => {
    // Login skeleton — adapt cho project khi expand
    // await page.goto('/login');
  });


  test('TC-001-E2E: Tạo đơn TO_CAO hợp lệ tự sinh STT [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-002-E2E: Tạo đơn KHIEU_NAI hợp lệ [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-003-E2E: Tạo đơn KIEN_NGHI [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-004-E2E: Tạo đơn PHAN_ANH [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-005-E2E: Ward officer tự gán assignedTeamId [@GREEN @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-006-E2E: Draft STT preview trước save [@GREEN @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-007-E2E: List đơn thư default [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-008-E2E: Filter theo status MOI_TIEP_NHAN [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-009-E2E: Search theo stt + senderName [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-010-E2E: GET /linkable [@GREEN @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-011-E2E: GET /petitions/:id (route alias v0.67.1) [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-012-E2E: PUT update đơn thư với expectedUpdatedAt [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Update
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-013-E2E: Convert đơn thư → Vụ án (atomic) [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-014-E2E: Convert → Vụ việc [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-015-E2E: Dispatcher assign đơn thư [@GREEN @P1]', async ({ page }) => {
    // Module: Petitions.Assign
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-016-E2E: Export Excel danh sách [@GREEN @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-017-E2E: Export document Word (PHIEU_DE_XUAT) [@GREEN @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-018-E2E: Soft-delete đơn thư [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Delete
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-019-E2E: ADMIN restore [@GREEN @P0]', async ({ page }) => {
    // Module: Petitions.Restore
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-020-E2E: GET /petitions/stats count theo 7 status [@GREEN @P2]', async ({ page }) => {
    // Module: Petitions.Stats
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-021-E2E: Thiếu senderName [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-022-E2E: Thiếu petitionType [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-023-E2E: petitionType không thuộc enum [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-024-E2E: receivedDate tương lai [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-025-E2E: STT trùng (manual) [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-026-E2E: senderEmail format sai [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-027-E2E: senderPhone format sai [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-028-E2E: OCC stale expectedUpdatedAt [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Update
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-029-E2E: Convert đơn đã linked Case [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-030-E2E: Convert thiếu caseName [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-031-E2E: Convert thiếu expectedUpdatedAt (chống race) [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-032-E2E: Convert đơn đã soft-delete [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-033-E2E: Convert với jurisdiction enum sai [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-034-E2E: GET không JWT [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Auth
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-035-E2E: User không có read:Petition [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Auth
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-036-E2E: Non-creator non-admin xóa [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Delete
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-037-E2E: Xóa đơn đã DA_CHUYEN_VU_AN [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Delete
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-038-E2E: Non-ADMIN restore [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Restore
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-039-E2E: User Team A xem petition Team B [@RED @P0]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-040-E2E: limit > 100 [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-041-E2E: fromDate > toDate [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-042-E2E: Non-dispatcher assign [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Assign
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-043-E2E: Assign thiếu assignedTeamId [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Assign
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-044-E2E: export-document docType không thuộc 6 template [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-045-E2E: Batch export ZIP với 0 ids [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-046-E2E: detailContent có HTML/script không sanitize [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-047-E2E: Senderr name > 255 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-048-E2E: summary > 2000 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-049-E2E: assignedToId không tồn tại [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-050-E2E: deadline tự nhập < receivedDate [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-051-E2E: Update đơn đã soft-delete [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Update
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-052-E2E: sortBy injection [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-053-E2E: Export rate limit 5/min [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-054-E2E: Convert race — 2 user cùng convert [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-055-E2E: Bulk assign khác đơn vị [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Bulk
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-056-E2E: Bulk delete >100 ids [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Bulk
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-057-E2E: GET stats với status filter — phải strip [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-058-E2E: DocumentNumberEngine fail giữa transaction [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-059-E2E: unit > 255 ký tự [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-060-E2E: export-word legacy bị disable [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-061-E2E: Tạo đơn có notes chứa SQL keyword [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-062-E2E: baoCaoBanGiamDoc enum không hợp lệ [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-063-E2E: Cache HIT ở user A leak data sang user B [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-064-E2E: Search với % wildcard SQL [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-065-E2E: senderName = 1 ký tự (min) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-066-E2E: senderName = 255 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-067-E2E: summary = 2000 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-068-E2E: limit=1 [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-069-E2E: limit=100 [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-070-E2E: listLinkable limit=50 default [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-071-E2E: STT counter rollover năm mới [@BOUNDARY @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-072-E2E: status 7 partition [@EP @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-073-E2E: petitionType 4 partition [@EP @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-074-E2E: overdue=true vs false [@EP @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-075-E2E: docType 6 template values [@EP @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-076-E2E: MOI_TIEP_NHAN → DANG_XU_LY [@STATE @P0]', async ({ page }) => {
    // Module: Petitions.State
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-077-E2E: DANG_XU_LY → CHO_PHE_DUYET [@STATE @P0]', async ({ page }) => {
    // Module: Petitions.State
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-078-E2E: CHO_PHE_DUYET → DA_GIAI_QUYET [@STATE @P0]', async ({ page }) => {
    // Module: Petitions.State
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-079-E2E: Convert-case auto đặt status=DA_CHUYEN_VU_AN [@STATE @P0]', async ({ page }) => {
    // Module: Petitions.State
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-080-E2E: Convert-incident auto đặt status=DA_CHUYEN_VU_VIEC [@STATE @P0]', async ({ page }) => {
    // Module: Petitions.State
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-081-E2E: DA_LUU_DON là terminal [@STATE @P1]', async ({ page }) => {
    // Module: Petitions.State
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-082-E2E: Deadline auto-calc theo petitionType (DT) [@DECISION @P0]', async ({ page }) => {
    // Module: Petitions.Decision
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-083-E2E: DataScope filter — 4 role combinations [@DECISION @P0]', async ({ page }) => {
    // Module: Petitions.Decision
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-084-E2E: SQL Injection trong search [@SECURITY @P0]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-085-E2E: XSS senderName [@SECURITY @P0]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-086-E2E: XSS detailContent (RichText) [@SECURITY @P0]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-087-E2E: IDOR GET /:id khác team [@SECURITY @P0]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-088-E2E: Mass assignment enteredById [@SECURITY @P0]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-089-E2E: CSRF POST cross-origin [@SECURITY @P0]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-090-E2E: Path traversal export filename [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-091-E2E: Sensitive PII trong export — masking [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-092-E2E: Rate limit list endpoint [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-093-E2E: Convert race — bypass optimistic lock với expectedUpdatedAt giả [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-094-E2E: docx template path injection [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-095-E2E: Audit log không chứa password/token [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-096-E2E: CORS — preflight evil origin [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-097-E2E: Unicode senderName tiếng Việt [@DATA @P1]', async ({ page }) => {
    // Module: Petitions.Data
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-098-E2E: Phone E.164 vs local [@DATA @P1]', async ({ page }) => {
    // Module: Petitions.Data
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-099-E2E: Trim senderName [@DATA @P1]', async ({ page }) => {
    // Module: Petitions.Data
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-100-E2E: Date receivedDate UTC+7 [@DATA @P1]', async ({ page }) => {
    // Module: Petitions.Data
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-101-E2E: Empty optional fields → null [@DATA @P2]', async ({ page }) => {
    // Module: Petitions.Data
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-102-E2E: 2 user concurrent create cùng giây — STT unique [@EDGE @P1]', async ({ page }) => {
    // Module: Petitions.Race
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-103-E2E: Convert sau khi đã merge document [@EDGE @P1]', async ({ page }) => {
    // Module: Petitions.Edge
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-104-E2E: Stats DB rỗng [@EDGE @P2]', async ({ page }) => {
    // Module: Petitions.Stats
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-105-E2E: Form keyboard tab order [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-106-E2E: Label htmlFor đầy đủ [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-107-E2E: Contrast badge 7 status ≥ 4.5 [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-108-E2E: Error aria-live announce [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-109-E2E: Convert modal trap focus [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-110-E2E: PageHeader có heading h1 [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-111-E2E: Chrome 130 Win [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-112-E2E: Firefox 130 [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-113-E2E: Edge 130 [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-114-E2E: Safari 17 macOS [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-115-E2E: Mobile 375x667 [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-116-E2E: Tablet 768x1024 [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-117-E2E: List 1000 đơn < 2s [@PERFORMANCE @P0]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-118-E2E: Convert đơn có 50 documents < 5s [@PERFORMANCE @P1]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-119-E2E: Export 5000 record < 30s [@PERFORMANCE @P2]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-120-E2E: STT auto-gen + DocumentNumberLog ghi đầy đủ [@INTEGRATION @P0]', async ({ page }) => {
    // Module: Petitions.Doc
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-121-E2E: Assign → notification cho assignedToId [@INTEGRATION @P0]', async ({ page }) => {
    // Module: Petitions.Notify
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-122-E2E: senderBirthYear < 1900 [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-123-E2E: senderBirthYear > năm hiện tại [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-124-E2E: Update senderName trên đơn đã DA_CHUYEN_VU_AN [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Update
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-125-E2E: Bulk-assign body ids rỗng [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Bulk
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-126-E2E: export/duplicates với date range > 365 ngày [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Export
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-127-E2E: Convert-incident thiếu name [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-128-E2E: raSoatTrung enum không hợp lệ [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-129-E2E: Export-document với 6 docType lần lượt → 6 SeriesKey khác [@INTEGRATION @P1]', async ({ page }) => {
    // Module: Petitions.Doc
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-130-E2E: Convert đơn đã linked Incident [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Convert
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-131-E2E: Ward page WardPetitionsPage user thường không thấy [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-132-E2E: Bulk action checkbox có label SR [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-133-E2E: Overdue badge có aria-label đầy đủ ngày [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-134-E2E: PWA install offline read cached petitions [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-135-E2E: Print stylesheet cho export-document preview [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-136-E2E: Tạo đơn không thuộc đơn vị mình (unit param) [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-137-E2E: Update senderEmail format sai [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Update
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-138-E2E: ZIP slip qua batch-export filename [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-139-E2E: Body content-type không phải application/json [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Create
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-140-E2E: GET /:id/journey với page=0 [@RED @P1]', async ({ page }) => {
    // Module: Petitions.Read
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-141-E2E: Document export OOXML macro injection [@SECURITY @P1]', async ({ page }) => {
    // Module: Petitions.Security
    await page.goto('/petitions', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });

});