// Ủy thác Điều tra (UTDT) — E2E UI layer (Layer 2)
// Auto-generated by gen_uat_specs.py
import { test, expect } from '@playwright/test';

test.describe('UAT E2E — Ủy thác Điều tra (UTDT)', () => {
  test.beforeEach(async ({ page }) => {
    // Login skeleton — adapt cho project khi expand
    // await page.goto('/login');
  });


  test('TC-001-E2E: Tạo case UTDT hợp lệ với donViGiao + soQuyetDinhUyThac [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-002-E2E: Tạo UTDT với loaiUyThac=CHUYEN_DON_NGUON_TIN [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-003-E2E: Tạo UTDT với loaiUyThac=UY_THAC_GIAI_QUYET [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-004-E2E: Tạo Delegation độc lập (workflow SCR-PF-04) [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-005-E2E: Delegation với relatedCaseId [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-006-E2E: GET /cases?caseType=UY_THAC_DIEU_TRA listing [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-007-E2E: GET /cases/utdt-stats 4 trạng thái phản hồi [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-008-E2E: Filter theo trangThaiPhanHoi=QUA_HAN [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-009-E2E: Filter theo donViGiao [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-010-E2E: Filter date range ngayTiepNhan [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-011-E2E: Cập nhật kết quả UTDT (ketQuaUyThac + ngayTraKetQua) [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-012-E2E: Cập nhật metadata utdt_lyDoKhongThucHienDuoc [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-013-E2E: CaseFormPage hiển thị tab ’Thông tin Ủy thác’ tại vị trí 2 [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-014-E2E: Row click → /uy-thac-dieu-tra/:id/edit redirect /cases/:id/edit [@GREEN @P0]', async ({ page }) => {
    // Module: UTDT.Route
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-015-E2E: Update Delegation status PENDING → RECEIVED [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-016-E2E: Delegation RECEIVED → COMPLETED có completedDate [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-017-E2E: Soft-delete Delegation bởi creator [@GREEN @P1]', async ({ page }) => {
    // Module: UTDT.Delete
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-018-E2E: Tạo UTDT thiếu donViGiao (v0.67.3.0 bắt buộc) [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-019-E2E: caseProvenance=UY_THAC_DIEU_TRA nhưng caseType=REGULAR [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-020-E2E: loaiUyThac enum không hợp lệ [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-021-E2E: donViGiao > 500 ký tự [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-022-E2E: soQuyetDinhUyThac > 100 ký tự [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-023-E2E: loaiThongTin > 200 ký tự [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-024-E2E: thoiHanUyThac < ngayTiepNhan [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-025-E2E: ngayTraKetQua < ngayTiepNhan [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-026-E2E: Delegation thiếu receivingUnit [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-027-E2E: Delegation thiếu content [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-028-E2E: Delegation status không thuộc enum (XYZ) [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-029-E2E: delegationNumber manual trùng [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-030-E2E: relatedCaseId không tồn tại [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-031-E2E: User Team A xem UTDT Team B (IDOR) [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-032-E2E: GET /delegations/X khác scope [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Delegation
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-033-E2E: GET không JWT [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Auth
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-034-E2E: User không có write:Case create UTDT [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Auth
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-035-E2E: Delegation xóa bởi non-creator non-admin [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Delete
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-036-E2E: GET utdt-stats không strip caseType filter [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-037-E2E: GET utdt-stats không strip trangThaiPhanHoi [@RED @P0]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-038-E2E: Filter trangThaiPhanHoi không hợp lệ [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-039-E2E: investigatorName search SQL injection [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-040-E2E: Update kết quả UTDT trên case không phải UTDT [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-041-E2E: Tab ’Thông tin Ủy thác’ hiển thị khi caseProvenance khác UY_THAC_DIEU_TRA [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-042-E2E: Đổi caseProvenance khác → tab UTDT ẩn ngay [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-043-E2E: Update OCC stale [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-044-E2E: limit > 100 [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-045-E2E: Sort theo donViGiao injection [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-046-E2E: loaiUyThac=null nhưng vẫn submit [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-047-E2E: ngayTraKetQua tương lai (>now) [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-048-E2E: Hidden field utdt_lyDoKhongThucHienDuoc bypass [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-049-E2E: Stats với case caseType=REGULAR (không UTDT) — phải bỏ qua [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-050-E2E: Bulk assign UTDT khác đơn vị [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Bulk
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-051-E2E: Đổi caseType từ UY_THAC_DIEU_TRA → REGULAR [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-052-E2E: Xóa UTDT case có sub-entities [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Delete
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-053-E2E: Update completedDate < createdAt [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Delegation
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-054-E2E: Delete với non-creator non-admin [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Delegation
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-055-E2E: Tạo case UTDT với linkedPetitionId (mâu thuẫn provenance) [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-056-E2E: donViGiao = 500 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-057-E2E: donViGiao = 1 ký tự (min) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-058-E2E: soQuyetDinhUyThac = 100 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-059-E2E: loaiThongTin = 200 (max) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-060-E2E: thoiHanUyThac = now (boundary QUA_HAN) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-061-E2E: thoiHanUyThac = now-1s (QUA_HAN) [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-062-E2E: limit=100 [@BOUNDARY @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-063-E2E: loaiUyThac 3 enum partition [@EP @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-064-E2E: trangThaiPhanHoi 4 enum + default [@EP @P1]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-065-E2E: DelegationStatus 3 partition [@EP @P1]', async ({ page }) => {
    // Module: UTDT.Delegation
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-066-E2E: Delegation PENDING → RECEIVED [@STATE @P0]', async ({ page }) => {
    // Module: UTDT.State
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-067-E2E: Delegation RECEIVED → COMPLETED [@STATE @P0]', async ({ page }) => {
    // Module: UTDT.State
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-068-E2E: COMPLETED → bất kỳ (terminal) [@STATE @P0]', async ({ page }) => {
    // Module: UTDT.State
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-069-E2E: trangThaiPhanHoi computed precedence DA_PHAN_HOI > KHONG_THUC_HIEN_DUOC [@STATE @P0]', async ({ page }) => {
    // Module: UTDT.State
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-070-E2E: trangThaiPhanHoi precedence QUA_HAN < KHONG_THUC_HIEN_DUOC [@STATE @P0]', async ({ page }) => {
    // Module: UTDT.State
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-071-E2E: Decision Table — trangThaiPhanHoi 16 combination (4 fields × 2 state) [@DECISION @P0]', async ({ page }) => {
    // Module: UTDT.Decision
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-072-E2E: caseProvenance × caseType validation CHECK constraint [@DECISION @P0]', async ({ page }) => {
    // Module: UTDT.Decision
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-073-E2E: SQL Injection trong donViGiao filter [@SECURITY @P0]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-074-E2E: XSS donViGiao + ketQuaUyThac [@SECURITY @P0]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-075-E2E: IDOR — GET delegation cross-user [@SECURITY @P0]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-076-E2E: Mass assignment delegationNumber để override engine [@SECURITY @P0]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-077-E2E: CSRF POST cross-origin [@SECURITY @P0]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-078-E2E: Privilege escalation — non-dispatcher reassign delegation [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-079-E2E: Rate limit list UTDT [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-080-E2E: Token replay sau khi user.dataScope thay đổi [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-081-E2E: Audit log delegation lưu actor + diff [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-082-E2E: donViGiao tiếng Việt có dấu [@DATA @P1]', async ({ page }) => {
    // Module: UTDT.Data
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-083-E2E: Trim donViGiao leading/trailing [@DATA @P1]', async ({ page }) => {
    // Module: UTDT.Data
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-084-E2E: ngayTiepNhan ISO UTC+7 [@DATA @P1]', async ({ page }) => {
    // Module: UTDT.Data
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-085-E2E: metadata JSON sâu (nested objects) [@DATA @P2]', async ({ page }) => {
    // Module: UTDT.Data
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-086-E2E: Concurrent update kết quả + lý do không thực hiện [@EDGE @P1]', async ({ page }) => {
    // Module: UTDT.Edge
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-087-E2E: thoiHanUyThac vượt 365 ngày [@EDGE @P1]', async ({ page }) => {
    // Module: UTDT.Edge
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-088-E2E: Stats khi 0 UTDT [@EDGE @P2]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-089-E2E: Tab UTDT navigation bằng arrow keys [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-090-E2E: donViGiao field label htmlFor [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-091-E2E: Contrast 4 trangThaiPhanHoi badge [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-092-E2E: Required field ’Đơn vị giao’ có dấu * + aria-required [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-093-E2E: Error catch real-error (v0.67.3.0) đọc qua live region [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-094-E2E: Chrome 130 Win [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-095-E2E: Firefox 130 [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-096-E2E: Edge 130 [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-097-E2E: Safari 17 [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-098-E2E: Mobile 375x667 — tab UTDT scroll horizontal [@COMPAT @P1]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-099-E2E: Tablet 768x1024 [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });


  test('TC-100-E2E: List 1000 UTDT < 2s [@PERFORMANCE @P0]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-101-E2E: utdt-stats 4 parallel count < 1s [@PERFORMANCE @P1]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-102-E2E: Concurrent 30 create delegation [@PERFORMANCE @P2]', async ({ page }) => {
    // PERFORMANCE test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual PERFORMANCE verification required');
  });


  test('TC-103-E2E: create delegation emit utdt.assigned → SSE assignedTo [@INTEGRATION @P0]', async ({ page }) => {
    // Module: UTDT.Notify
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-104-E2E: Case UTDT khi caseProvenance=UY_THAC_DIEU_TRA tự force caseType [@INTEGRATION @P0]', async ({ page }) => {
    // Module: UTDT.Case
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-105-E2E: FE list UTDT với 6 filter combine (caseType+donViGiao+loaiUyThac+date+state+investigator) [@INTEGRATION @P1]', async ({ page }) => {
    // Module: UTDT.Filter
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-106-E2E: caseProvenance khác UY_THAC_DIEU_TRA nhưng truyền donViGiao [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-107-E2E: ngayTraKetQua set nhưng ketQuaUyThac trống [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Create
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-108-E2E: PATCH /:id/assign vào non-investigator [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-109-E2E: POST /delegations content > 5000 ký tự [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Delegation
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-110-E2E: receivingUnit > 255 ký tự [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Delegation
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-111-E2E: investigatorName chứa wildcard SQL [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Read
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-112-E2E: Save UTDT form nhưng API throw — error visible (v0.67.3.0) [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-113-E2E: GET utdt-stats khi DB chỉ có case không UTDT [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Stats
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-114-E2E: Delete UTDT có Delegation liên kết [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Delete
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-115-E2E: Tab UTDT click trực tiếp URL khi caseProvenance khác [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Form
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-116-E2E: /uy-thac-dieu-tra/:id/edit với id không tồn tại [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Route
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-117-E2E: Update Delegation status thẳng PENDING → COMPLETED [@RED @P1]', async ({ page }) => {
    // Module: UTDT.Update
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-118-E2E: Path traversal qua delegationNumber regex [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-119-E2E: NoSQL/Prisma operator injection trong filter [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-120-E2E: Sensitive PII export — donViGiao + investigator name [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-121-E2E: Force browse /cases/X/edit của case UTDT đơn vị khác [@SECURITY @P1]', async ({ page }) => {
    // Module: UTDT.Security
    await page.goto('/uy-thac-dieu-tra', { waitUntil: 'domcontentloaded' });
    // 3 UI assertions: URL + body visible + có content
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.length ?? 0).toBeGreaterThan(0);
  });


  test('TC-122-E2E: Section UTDT có heading h2 + landmark role [@A11Y @P1]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-123-E2E: Date picker thoiHanUyThac keyboard accessible [@A11Y @P2]', async ({ page }) => {
    // A11Y test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual A11Y verification required');
  });


  test('TC-124-E2E: PWA offline xem UTDT cached [@COMPAT @P2]', async ({ page }) => {
    // COMPAT test — kiểm thủ công (axe-core / lighthouse / k6)
    test.skip(true, 'Manual COMPAT verification required');
  });

});