// Auto-generated by scripts/uat_spec_generator.py — uat-test-runner
// Feature: utdt | Source: docs/uat/utdt/uat.json
// Layer: UI E2E Chromium (Page Object Model, ≥3 UI assertion/TC)
// Total TC: 110

import { test, expect } from '@playwright/test';
import { UTDTPage } from '../pages/UTDTPage';
import { loginToPage } from '../helpers/auth';

test.describe('UTDT — UAT E2E layer', () => {
  test('TC-UTDT-001-E2E: [P0] Tạo UTDT đầy đủ (caseType + loaiUyThac + donViGiao + ngày)', async ({ page }) => {
    // Pre: -
    // Steps: POST {name:\'UTDT-{{random}}\', caseProvenance:\'UY_THAC_DIEU_TRA\', caseType:\'UY_THAC_DIEU_TRA\', loaiUyThac:\'UY_THAC_DIEU_TRA\', donViGiao:\'PC01 Hà Nội\', soQuyetDinhUyThac:\'58/2026/UTDT\', ngay
    // Expected: HTTP 201, id≠null, computed TrangThaiPhanHoi=CHUA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-002-E2E: [P0] Tạo UTDT loaiUyThac=CHUYEN_DON_NGUON_TIN', async ({ page }) => {
    // Pre: -
    // Steps: POST {caseType:\'UY_THAC_DIEU_TRA\', loaiUyThac:\'CHUYEN_DON_NGUON_TIN\', ...}
    // Expected: HTTP 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-003-E2E: [P0] Tạo UTDT loaiUyThac=UY_THAC_GIAI_QUYET', async ({ page }) => {
    // Pre: -
    // Steps: POST loaiUyThac=UY_THAC_GIAI_QUYET
    // Expected: HTTP 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-004-E2E: [P0] List UTDT cases (caseType filter explicit)', async ({ page }) => {
    // Pre: DB có UTDT
    // Steps: GET ?caseType=UY_THAC_DIEU_TRA
    // Expected: HTTP 200, items chỉ UTDT
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-005-E2E: [P0] List default exclude UTDT (caseType=REGULAR implicit)', async ({ page }) => {
    // Pre: DB mix REGULAR + UTDT
    // Steps: GET /api/v1/cases (không caseType)
    // Expected: HTTP 200, items không có UTDT
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-006-E2E: [P0] UTDT stats 4 TrangThaiPhanHoi', async ({ page }) => {
    // Pre: DB có UTDT ở 4 state
    // Steps: GET /utdt-stats
    // Expected: HTTP 200, byTrangThai = {DA_PHAN_HOI, KHONG_THUC_HIEN_DUOC, QUA_HAN, CHUA_PHAN_HOI}
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-007-E2E: [P0] Update ketQuaUyThac + ngayTraKetQua → state DA_PHAN_HOI', async ({ page }) => {
    // Pre: UTDT chưa có ketQua
    // Steps: PUT {ketQuaUyThac:\'Đã điều tra xong\', ngayTraKetQua:\'2026-07-15\'}
    // Expected: HTTP 200, computed state=DA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-008-E2E: [P0] Update metadata.lyDoKhongThucHienDuoc → state KHONG_THUC_HIEN_DUOC', async ({ page }) => {
    // Pre: -
    // Steps: PUT {metadata:{lyDoKhongThucHienDuoc:\'Đối tượng đã chuyển nơi cư trú\'}}
    // Expected: HTTP 200, computed state=KHONG_THUC_HIEN_DUOC
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-009-E2E: [P0] Filter UTDT DA_PHAN_HOI', async ({ page }) => {
    // Pre: DB có UTDT đã phản hồi
    // Steps: GET ?caseType=UY_THAC_DIEU_TRA&trangThaiPhanHoi=DA_PHAN_HOI
    // Expected: HTTP 200, items đều thỏa ketQua≠null AND ngayTra≠null
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-010-E2E: [P0] Filter UTDT QUA_HAN', async ({ page }) => {
    // Pre: DB có UTDT quá hạn
    // Steps: GET ?trangThaiPhanHoi=QUA_HAN
    // Expected: HTTP 200, items đều thoiHanUyThac<now + ketQua=null
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-011-E2E: [P0] Filter UTDT theo donViGiao (substring)', async ({ page }) => {
    // Pre: -
    // Steps: GET ?caseType=UY_THAC_DIEU_TRA&donViGiao=PC01
    // Expected: HTTP 200, items.donViGiao chứa \'PC01\' (case-insensitive)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-012-E2E: [P1] Filter UTDT date range', async ({ page }) => {
    // Pre: -
    // Steps: GET ?ngayTiepNhanFrom=2026-01-01&ngayTiepNhanTo=2026-06-30
    // Expected: HTTP 200, items.ngayTiepNhan trong khoảng
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-013-E2E: [P1] Filter UTDT theo tên ĐTV', async ({ page }) => {
    // Pre: -
    // Steps: GET ?investigatorName=Nguyễn
    // Expected: HTTP 200, items investigator name match
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-014-E2E: [P0] Xem chi tiết UTDT — đủ field', async ({ page }) => {
    // Pre: -
    // Steps: GET /api/v1/cases/{{utdt_id}}
    // Expected: HTTP 200, response có đủ donViGiao, soQuyetDinhUyThac, loaiUyThac, ngày…, computed trangThaiPhanHoi
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-015-E2E: [P0] caseType=UY_THAC_DIEU_TRA nhưng caseProvenance khác → 400 hoặc bị reject', async ({ page }) => {
    // Pre: -
    // Steps: POST {caseType:\'UY_THAC_DIEU_TRA\', caseProvenance:\'DIRECT_DISCOVERY\'}
    // Expected: HTTP 400 nếu service enforce match, hoặc 201 với mismatch warning
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-016-E2E: [P0] loaiUyThac ngoài enum → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST {caseType:\'UY_THAC_DIEU_TRA\', loaiUyThac:\'INVALID\'}
    // Expected: HTTP 400, IsEnum LoaiUyThac fail
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-017-E2E: [P0] donViGiao vượt 500 ký tự → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST donViGiao length=501
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-018-E2E: [P0] soQuyetDinhUyThac vượt 100 ký tự → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST soQuyetDinhUyThac length=101
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-019-E2E: [P0] ngayTiepNhan sai format → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST ngayTiepNhan=\'30/05/2026\'
    // Expected: HTTP 400, IsDateString
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-020-E2E: [P0] thoiHanUyThac sai format → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST thoiHanUyThac=\'soon\'
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-021-E2E: [P0] loaiThongTin vượt 200 ký tự → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST loaiThongTin length=201
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-022-E2E: [P0] Query caseType ngoài enum → 400', async ({ page }) => {
    // Pre: -
    // Steps: GET ?caseType=INVALID
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-023-E2E: [P0] trangThaiPhanHoi ngoài 4 value → 400', async ({ page }) => {
    // Pre: -
    // Steps: GET ?trangThaiPhanHoi=NEW_STATE
    // Expected: HTTP 400, IsIn 4 values
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-024-E2E: [P0] utdt-stats không scope → 403', async ({ page }) => {
    // Pre: User không có read/Case
    // Steps: GET /utdt-stats
    // Expected: HTTP 403
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-025-E2E: [P0] UTDT thiếu caseProvenance → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST {caseType:\'UY_THAC_DIEU_TRA\'} không caseProvenance
    // Expected: HTTP 400, caseProvenance bắt buộc
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-026-E2E: [P0] Update UTDT không thuộc scope → 403/404', async ({ page }) => {
    // Pre: -
    // Steps: PUT other team UTDT
    // Expected: HTTP 403/404
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-027-E2E: [P1] PUT đổi caseType từ UTDT → REGULAR → 400 (immutable)', async ({ page }) => {
    // Pre: -
    // Steps: PUT {caseType:\'REGULAR\'}
    // Expected: HTTP 400 hoặc strip
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-028-E2E: [P1] PUT ketQuaUyThac chỉ có ngayTraKetQua không có ketQua → state vẫn CHUA', async ({ page }) => {
    // Pre: UTDT chưa phản hồi
    // Steps: PUT {ngayTraKetQua:\'2026-07-15\'} không ketQuaUyThac
    // Expected: HTTP 200, computed vẫn CHUA_PHAN_HOI (cần cả 2 mới DA_PHAN_HOI)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-029-E2E: [P1] UTDT search > 200 chars → 400', async ({ page }) => {
    // Pre: -
    // Steps: GET ?search=<201>&caseType=UY_THAC_DIEU_TRA
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-030-E2E: [P0] UTDT với ngayTiepNhan tương lai → 400 hoặc warning', async ({ page }) => {
    // Pre: -
    // Steps: POST ngayTiepNhan=\'2027-01-01\'
    // Expected: HTTP 201 (validator chỉ ISO) hoặc 400 nếu rule
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-031-E2E: [P0] utdt-stats không phải UTDT scope leak Regular case → fail', async ({ page }) => {
    // Pre: -
    // Steps: Verify response only counts UTDT cases
    // Expected: byTrangThai counts đều ≤ tổng UTDT cases, không lẫn Regular
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-032-E2E: [P0] UTDT với thoiHanUyThac < ngayTiepNhan → 400/warning', async ({ page }) => {
    // Pre: -
    // Steps: POST {ngayTiepNhan:\'2026-05-30\', thoiHanUyThac:\'2026-05-01\'}
    // Expected: HTTP 400 nếu rule, hoặc 201 với log
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-033-E2E: [P0] trangThaiPhanHoi=QUA_HAN nhưng thiếu caseType=UY_THAC_DIEU_TRA → 200 nhưng items khác kỳ vọng', async ({ page }) => {
    // Pre: -
    // Steps: GET ?trangThaiPhanHoi=QUA_HAN không caseType
    // Expected: HTTP 200 — filter apply trên REGULAR (default) → có thể empty
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-034-E2E: [P0] UTDT với soQuyetDinhUyThac trùng (Mẫu 58 conflict) → 409 nếu unique', async ({ page }) => {
    // Pre: -
    // Steps: POST 2 lần cùng soQuyetDinhUyThac
    // Expected: HTTP 409 nếu unique constraint, hoặc 201 cả 2 nếu chỉ là string
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-035-E2E: [P1] PUT UTDT đã DA_PHAN_HOI — đổi ngayTraKetQua = null → state đổi', async ({ page }) => {
    // Pre: UTDT DA_PHAN_HOI
    // Steps: PUT {ngayTraKetQua:null}
    // Expected: HTTP 200, computed state ngược về CHUA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-036-E2E: [P1] loaiUyThac filter ngoài enum → 400', async ({ page }) => {
    // Pre: -
    // Steps: GET ?loaiUyThac=INVALID
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-037-E2E: [P1] ngayTiepNhanFrom sai format → 400', async ({ page }) => {
    // Pre: -
    // Steps: GET ?ngayTiepNhanFrom=\'hôm qua\'
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-038-E2E: [P1] ngayTiepNhanFrom > ngayTiepNhanTo → 200 empty', async ({ page }) => {
    // Pre: -
    // Steps: GET fromDate > toDate
    // Expected: HTTP 200, items=[]
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-039-E2E: [P0] UTDT thiếu donViGiao → 201 (optional) hoặc 400 nếu rule', async ({ page }) => {
    // Pre: -
    // Steps: POST không donViGiao
    // Expected: HTTP 201 (vì optional theo DTO)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-040-E2E: [P0] DELETE UTDT (kế thừa case delete rules) — DA_PHAN_HOI thì cấm xóa hoặc cho phép', async ({ page }) => {
    // Pre: -
    // Steps: DELETE UTDT DA_PHAN_HOI
    // Expected: Verify rule: cho phép soft-delete với reason
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-041-E2E: [P0] utdt-stats với scope filter (donViGiao) → counts đúng theo filter', async ({ page }) => {
    // Pre: -
    // Steps: GET /utdt-stats?donViGiao=PC01
    // Expected: HTTP 200, byTrangThai chỉ tính UTDT có donViGiao=PC01
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-042-E2E: [P1] PUT metadata.lyDoKhongThucHienDuoc=\'\' (empty) → state vẫn CHUA', async ({ page }) => {
    // Pre: -
    // Steps: PUT {metadata:{lyDoKhongThucHienDuoc:\'\'}}
    // Expected: HTTP 200, computed CHUA_PHAN_HOI (empty không count)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-043-E2E: [P1] donViGiao = 500 ký tự (max) → 201', async ({ page }) => {
    // Pre: -
    // Steps: POST donViGiao length=500
    // Expected: HTTP 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-044-E2E: [P1] donViGiao = 501 → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST donViGiao length=501
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-045-E2E: [P1] soQuyetDinhUyThac = 100 ký tự (max)', async ({ page }) => {
    // Pre: -
    // Steps: POST length=100
    // Expected: HTTP 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-046-E2E: [P1] soQuyetDinhUyThac = 101 → 400', async ({ page }) => {
    // Pre: -
    // Steps: POST length=101
    // Expected: HTTP 400
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-047-E2E: [P1] loaiThongTin = 200 ký tự (max)', async ({ page }) => {
    // Pre: -
    // Steps: POST length=200
    // Expected: HTTP 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-048-E2E: [P0] thoiHanUyThac = now exactly — state QUA_HAN không trigger (≤)', async ({ page }) => {
    // Pre: -
    // Steps: PUT thoiHanUyThac={{now}}
    // Expected: HTTP 200, computed state CHUA_PHAN_HOI (vì < not ≤)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-049-E2E: [P0] thoiHanUyThac = now-1ms — state QUA_HAN trigger', async ({ page }) => {
    // Pre: -
    // Steps: PUT thoiHanUyThac={{now-1ms}}
    // Expected: HTTP 200, computed QUA_HAN
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-050-E2E: [P1] caseType filter empty string → 400 hoặc default', async ({ page }) => {
    // Pre: -
    // Steps: GET ?caseType=
    // Expected: HTTP 400 (IsEnum reject) hoặc 200 với default REGULAR
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-051-E2E: [P2] UTDT với loaiUyThac giống caseProvenance (cả 2 đều UY_THAC_DIEU_TRA)', async ({ page }) => {
    // Pre: -
    // Steps: POST {caseProvenance:\'UY_THAC_DIEU_TRA\', loaiUyThac:\'UY_THAC_DIEU_TRA\'}
    // Expected: HTTP 201 (cùng tên enum nhưng 2 enum khác nhau OK)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-052-E2E: [P1] LoaiUyThac đủ 3 partition', async ({ page }) => {
    // Pre: -
    // Steps: Loop {UY_THAC_DIEU_TRA, CHUYEN_DON_NGUON_TIN, UY_THAC_GIAI_QUYET}
    // Expected: 3 lần 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-053-E2E: [P1] trangThaiPhanHoi đủ 4 partition', async ({ page }) => {
    // Pre: DB có UTDT đủ 4 state
    // Steps: Loop 4 ?trangThaiPhanHoi
    // Expected: Mỗi truy vấn trả đúng tập
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-054-E2E: [P1] caseType partition (REGULAR vs UY_THAC_DIEU_TRA)', async ({ page }) => {
    // Pre: -
    // Steps: GET ?caseType=REGULAR rồi UY_THAC_DIEU_TRA
    // Expected: Items khác hẳn
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-055-E2E: [P2] donViGiao partition (PC01/PC02/CA Quận)', async ({ page }) => {
    // Pre: -
    // Steps: Loop 3 substring
    // Expected: Mỗi value trả đúng
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-056-E2E: [P2] loaiThongTin partition (Tố giác / Trình báo / Đề nghị / Kiến nghị)', async ({ page }) => {
    // Pre: -
    // Steps: Loop 4 strings
    // Expected: Match
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-057-E2E: [P2] sortBy partition (ngayTiepNhan/thoiHanUyThac/createdAt)', async ({ page }) => {
    // Pre: -
    // Steps: 3 sortBy × 2 sortOrder
    // Expected: 6 lần 200
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-058-E2E: [P1] ketQuaUyThac partition (short / long / empty)', async ({ page }) => {
    // Pre: -
    // Steps: 3 case: \'OK\', \'<300 chars>\', \'\'
    // Expected: 3 lần 200
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-059-E2E: [P2] investigatorName partition (full/partial/empty)', async ({ page }) => {
    // Pre: -
    // Steps: 3 case
    // Expected: Mỗi case trả đúng
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-060-E2E: [P0] Transition computed: CHUA_PHAN_HOI → DA_PHAN_HOI (set cả ketQua+ngayTra)', async ({ page }) => {
    // Pre: UTDT CHUA
    // Steps: PUT đủ 2 field
    // Expected: HTTP 200, computed DA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-061-E2E: [P0] State CHUA → KHONG_THUC_HIEN_DUOC (set metadata.lyDoKhongThucHienDuoc)', async ({ page }) => {
    // Pre: UTDT CHUA
    // Steps: PUT metadata.lyDoKhongThucHienDuoc=\'Đối tượng chết\'
    // Expected: HTTP 200, computed KHONG_THUC_HIEN_DUOC
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-062-E2E: [P0] State CHUA → QUA_HAN (auto khi thoiHanUyThac < now)', async ({ page }) => {
    // Pre: UTDT CHUA, thoiHanUyThac sắp hết
    // Steps: Wait until thoiHanUyThac < now (hoặc trigger cron)
    // Expected: computed QUA_HAN (không cần update DB, là computed)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-063-E2E: [P1] State QUA_HAN → DA_PHAN_HOI (trả kết quả muộn)', async ({ page }) => {
    // Pre: UTDT QUA_HAN
    // Steps: PUT {ketQuaUyThac, ngayTraKetQua}
    // Expected: HTTP 200, computed DA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-064-E2E: [P1] State KHONG_THUC_HIEN_DUOC → DA_PHAN_HOI (gỡ lyDo + set ketQua)', async ({ page }) => {
    // Pre: UTDT KHONG_THUC_HIEN_DUOC
    // Steps: PUT {metadata:{}, ketQuaUyThac, ngayTraKetQua}
    // Expected: HTTP 200, computed DA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-065-E2E: [P0] Decision matrix computed state — 4×3 (state × scenario)', async ({ page }) => {
    // Pre: -
    // Steps: 3 scenario mỗi state: (default), (with filter donViGiao), (with date range)
    // Expected: 12 cell counts đúng theo buildTrangThaiFilter
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-066-E2E: [P0] Decision matrix computed: ketQua × ngayTra × thoiHan × lyDo (truth table 16 cells)', async ({ page }) => {
    // Pre: -
    // Steps: 16 combination → compute expected state
    // Expected: Mỗi combo match TrangThaiPhanHoi spec
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-067-E2E: [P1] Decision matrix filter combo (caseType × trangThaiPhanHoi × loaiUyThac)', async ({ page }) => {
    // Pre: -
    // Steps: 2×4×3 = 24 cell sample
    // Expected: Mỗi truy vấn trả tập đúng (no leak Regular khi caseType=UTDT)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-068-E2E: [P0] UTDT XSS donViGiao', async ({ page }) => {
    // Pre: -
    // Steps: POST donViGiao=\'<script>alert(1)</script>PC01\'
    // Expected: HTTP 201, lưu literal, render UI escape
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-069-E2E: [P0] SQL injection trong donViGiao filter', async ({ page }) => {
    // Pre: -
    // Steps: GET ?donViGiao=\' OR 1=1; --
    // Expected: HTTP 200, ILIKE param safe, không trả tất cả
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-070-E2E: [P0] UTDT metadata.lyDoKhongThucHienDuoc — JSON injection', async ({ page }) => {
    // Pre: -
    // Steps: POST {metadata:{lyDoKhongThucHienDuoc:{nested:{}}}}
    // Expected: HTTP 201 (Prisma JSONB lưu raw), computed state KHONG_THUC_HIEN_DUOC (vì path[\'lyDoKhongThucHienDuoc\'] not Prisma.JsonNull)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-071-E2E: [P1] investigatorName injection — \'%\' wildcard', async ({ page }) => {
    // Pre: -
    // Steps: GET ?investigatorName=%
    // Expected: HTTP 200, không leak tất cả (ILIKE escape %)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-072-E2E: [P1] PUT UTDT ngayTraKetQua = future date', async ({ page }) => {
    // Pre: -
    // Steps: PUT ngayTraKetQua=\'2030-01-01\'
    // Expected: HTTP 200 (DTO chỉ ISO check) — có thể warning business
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-073-E2E: [P1] utdt-stats với scope filter wardId → counts đúng cho ward', async ({ page }) => {
    // Pre: -
    // Steps: GET /utdt-stats?wardId={{ward}}
    // Expected: counts chỉ tính UTDT trong ward
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-074-E2E: [P0] UTDT empty DB → stats 0/0/0/0', async ({ page }) => {
    // Pre: DB không có UTDT
    // Steps: GET /utdt-stats
    // Expected: HTTP 200, byTrangThai = {DA_PHAN_HOI:0, KHONG_THUC_HIEN_DUOC:0, QUA_HAN:0, CHUA_PHAN_HOI:0}
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-075-E2E: [P0] UTDT scope strict — officer team A không thấy UTDT team B', async ({ page }) => {
    // Pre: -
    // Steps: GET ?caseType=UY_THAC_DIEU_TRA
    // Expected: HTTP 200, items chỉ team A
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-076-E2E: [P0] VIEWER không write/Case → 403', async ({ page }) => {
    // Pre: -
    // Steps: POST UTDT với VIEWER
    // Expected: HTTP 403
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-077-E2E: [P0] PUT UTDT đã deleted → 410/404', async ({ page }) => {
    // Pre: -
    // Steps: PUT
    // Expected: HTTP 410/404
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-078-E2E: [P0] IDOR — UTDT team khác → 403/404', async ({ page }) => {
    // Pre: -
    // Steps: GET other team UTDT
    // Expected: HTTP 403/404
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-079-E2E: [P0] Stats không leak counts cross-team', async ({ page }) => {
    // Pre: -
    // Steps: GET utdt-stats với officer A, sau đó officer B — verify counts khác nhau theo scope
    // Expected: Counts strict theo dataScope
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-080-E2E: [P0] Prototype pollution metadata.__proto__', async ({ page }) => {
    // Pre: -
    // Steps: POST {metadata:{__proto__:{admin:true}}}
    // Expected: HTTP 201, không pollute
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-081-E2E: [P0] Mass assignment UTDT — gửi caseProvenance, createdById', async ({ page }) => {
    // Pre: -
    // Steps: PUT {caseProvenance:\'DIRECT_DISCOVERY\', createdById:\'attacker\'}
    // Expected: HTTP 400 (whitelist) hoặc strip
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-082-E2E: [P0] Audit log UTDT có UTDT-specific fields', async ({ page }) => {
    // Pre: -
    // Steps: POST UTDT + check audit_log
    // Expected: audit có donViGiao, soQuyetDinhUyThac trong oldValues/newValues
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-083-E2E: [P1] UTDT stats RATE LIMIT (chống mass query)', async ({ page }) => {
    // Pre: -
    // Steps: 100 GET /utdt-stats trong 60s
    // Expected: Sau threshold throttle 429
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-084-E2E: [P1] UTDT-related fields không leak qua /api/v1/cases (REGULAR)', async ({ page }) => {
    // Pre: -
    // Steps: GET /api/v1/cases?caseType=REGULAR
    // Expected: Items REGULAR có UTDT fields đều null/undefined
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-085-E2E: [P0] Assign UTDT — verify DispatchGuard', async ({ page }) => {
    // Pre: -
    // Steps: PATCH /assign UTDT
    // Expected: HTTP 200 cho admin với canDispatch
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-086-E2E: [P1] UTDT search bypass caseType — verify can NOT bypass', async ({ page }) => {
    // Pre: -
    // Steps: GET ?search=PC01 (UTDT donViGiao có PC01)
    // Expected: HTTP 200 — REGULAR mode default exclude UTDT, không leak UTDT name qua search
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-087-E2E: [P1] Verify counts buildTrangThaiFilter chính xác (đơn vị test)', async ({ page }) => {
    // Pre: DB seed 4 UTDT đúng 4 state
    // Steps: GET
    // Expected: Counts (1,1,1,1)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-088-E2E: [P1] UTDT donViGiao tiếng Việt + dấu', async ({ page }) => {
    // Pre: -
    // Steps: POST donViGiao=\'Công an Quận Đống Đa — PC01\'
    // Expected: HTTP 201, GET lại đúng
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-089-E2E: [P1] UTDT soQuyetDinhUyThac format chuẩn Mẫu 58', async ({ page }) => {
    // Pre: -
    // Steps: POST soQuyetDinhUyThac=\'58/2026/UTĐT-PC02\'
    // Expected: HTTP 201
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL chứa /cases').toContain('/cases');
    await expect(page.locator('body'), 'Body phải visible').toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    const fallback = page.locator('h1, h2, [data-testid$="-page"]');
    await expect(heading.or(fallback).first(), 'Heading nghiệp vụ phải hiện').toBeVisible();
  });
  test('TC-UTDT-090-E2E: [P0] caseType=UY_THAC_DIEU_TRA scope chặt + wardTeamId verify', async ({ page }) => {
    // Pre: -
    // Steps: GET ?caseType=UY_THAC_DIEU_TRA&wardTeamId={{other_team_ward}}
    // Expected: HTTP 200, items=[] nếu officer không có wardTeam khớp — không leak qua wardTeamId param
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-091-E2E: [P1] PUT UTDT thay đổi loaiUyThac giữa chừng', async ({ page }) => {
    // Pre: UTDT đang xử lý
    // Steps: PUT loaiUyThac từ UY_THAC_DIEU_TRA → CHUYEN_DON_NGUON_TIN
    // Expected: HTTP 200 (allowed) hoặc 400 nếu rule immutable
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-092-E2E: [P1] UTDT export/ward — verify chỉ UTDT trong ward', async ({ page }) => {
    // Pre: -
    // Steps: GET /export/ward với UTDT data
    // Expected: Excel chỉ chứa UTDT cases theo ward
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-093-E2E: [P1] PUT UTDT với expectedUpdatedAt stale → 409', async ({ page }) => {
    // Pre: -
    // Steps: PUT stale optimistic lock
    // Expected: HTTP 409
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-094-E2E: [P0] Journey UTDT — events specific (assign, update ketQua, status change)', async ({ page }) => {
    // Pre: -
    // Steps: GET /journey UTDT
    // Expected: HTTP 200, events có UTDT-specific (ketQua change, lyDoKhongThucHienDuoc set)
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-095-E2E: [P1] DELETE UTDT với reason hợp lệ', async ({ page }) => {
    // Pre: -
    // Steps: DELETE body {reason:\'UTDT bị thu hồi bởi đơn vị giao\'}
    // Expected: HTTP 200
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-096-E2E: [P1] Restore UTDT đã xóa mềm', async ({ page }) => {
    // Pre: -
    // Steps: POST /restore reason=\'Khôi phục theo yêu cầu PC01\'
    // Expected: HTTP 200, deletedAt=null
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // Negative scenario — verify error hoặc redirect
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toMatch(/\/cases|\/login/);
    await expect(page.locator('body')).toBeVisible();
    const bodyText = await page.locator('body').textContent();
    expect(bodyText, 'body có text').toBeTruthy();
  });
  test('TC-UTDT-097-E2E: [P1] Tab \'Thông tin Ủy thác\' keyboard nav', async ({ page }) => {
    // Pre: caseType=UTDT chọn
    // Steps: Tab qua các field UTDT
    // Expected: Focus visible mọi field section 1/2/3
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // A11Y check: auth + heading + landmark + focus
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL phải chứa /cases').toContain('/cases');
    const h1 = page.locator('h1').first();
    await expect(h1, 'H1 phải visible cho A11Y').toBeVisible();
    const mainLandmark = page.locator('main, [role="main"]').first();
    await expect(mainLandmark, 'Main landmark phải tồn tại').toBeVisible();
  });
  test('TC-UTDT-098-E2E: [P1] Conditional tab visibility — aria-hidden khi REGULAR', async ({ page }) => {
    // Pre: caseType=REGULAR
    // Steps: Inspect tab list
    // Expected: Tab Ủy thác có aria-hidden=\'true\' hoặc không render
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // A11Y check: auth + heading + landmark + focus
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL phải chứa /cases').toContain('/cases');
    const h1 = page.locator('h1').first();
    await expect(h1, 'H1 phải visible cho A11Y').toBeVisible();
    const mainLandmark = page.locator('main, [role="main"]').first();
    await expect(mainLandmark, 'Main landmark phải tồn tại').toBeVisible();
  });
  test('TC-UTDT-099-E2E: [P1] TrangThaiBadge contrast 4 state WCAG AA', async ({ page }) => {
    // Pre: -
    // Steps: Render 4 badge + measure
    // Expected: 4 pair ≥4.5:1
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // A11Y check: auth + heading + landmark + focus
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL phải chứa /cases').toContain('/cases');
    const h1 = page.locator('h1').first();
    await expect(h1, 'H1 phải visible cho A11Y').toBeVisible();
    const mainLandmark = page.locator('main, [role="main"]').first();
    await expect(mainLandmark, 'Main landmark phải tồn tại').toBeVisible();
  });
  test('TC-UTDT-100-E2E: [P1] Field loaiUyThac dropdown — aria-label + role=\'combobox\'', async ({ page }) => {
    // Pre: -
    // Steps: Inspect select
    // Expected: role=\'combobox\' aria-expanded
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // A11Y check: auth + heading + landmark + focus
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL phải chứa /cases').toContain('/cases');
    const h1 = page.locator('h1').first();
    await expect(h1, 'H1 phải visible cho A11Y').toBeVisible();
    const mainLandmark = page.locator('main, [role="main"]').first();
    await expect(mainLandmark, 'Main landmark phải tồn tại').toBeVisible();
  });
  test('TC-UTDT-101-E2E: [P2] Date input ngayTiepNhan + thoiHanUyThac — aria-describedby format hint', async ({ page }) => {
    // Pre: -
    // Steps: Inspect
    // Expected: Hint \'YYYY-MM-DD\' có aria-describedby
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // A11Y check: auth + heading + landmark + focus
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL phải chứa /cases').toContain('/cases');
    const h1 = page.locator('h1').first();
    await expect(h1, 'H1 phải visible cho A11Y').toBeVisible();
    const mainLandmark = page.locator('main, [role="main"]').first();
    await expect(mainLandmark, 'Main landmark phải tồn tại').toBeVisible();
  });
  test('TC-UTDT-102-E2E: [P2] UTDT-stats chips — focus order logic', async ({ page }) => {
    // Pre: -
    // Steps: Tab qua 4 chip
    // Expected: Order: DA_PHAN_HOI, KHONG_THUC_HIEN_DUOC, QUA_HAN, CHUA_PHAN_HOI
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    // A11Y check: auth + heading + landmark + focus
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url(), 'URL phải chứa /cases').toContain('/cases');
    const h1 = page.locator('h1').first();
    await expect(h1, 'H1 phải visible cho A11Y').toBeVisible();
    const mainLandmark = page.locator('main, [role="main"]').first();
    await expect(mainLandmark, 'Main landmark phải tồn tại').toBeVisible();
  });
  test('TC-UTDT-103-E2E: [P1] Chromium desktop', async ({ page }) => {
    // Pre: -
    // Steps: Open
    // Expected: Tab Ủy thác render
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    await expect(heading.or(page.locator('h1, h2')).first()).toBeVisible();
  });
  test('TC-UTDT-104-E2E: [P1] Firefox desktop', async ({ page }) => {
    // Pre: -
    // Steps: Open
    // Expected: OK
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    await expect(heading.or(page.locator('h1, h2')).first()).toBeVisible();
  });
  test('TC-UTDT-105-E2E: [P1] WebKit desktop', async ({ page }) => {
    // Pre: -
    // Steps: Open
    // Expected: Date picker UTDT
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    await expect(heading.or(page.locator('h1, h2')).first()).toBeVisible();
  });
  test('TC-UTDT-106-E2E: [P0] Mobile 375 — tab Ủy thác scrollable', async ({ page }) => {
    // Pre: -
    // Steps: Mobile viewport
    // Expected: Tab list overflow scroll horizontal
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await page.setViewportSize({ width: 375, height: 667 });
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    await expect(heading.or(page.locator('h1, h2')).first()).toBeVisible();
  });
  test('TC-UTDT-107-E2E: [P1] Tablet 768', async ({ page }) => {
    // Pre: -
    // Steps: Tablet viewport
    // Expected: Adapt
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    await page.setViewportSize({ width: 768, height: 1024 });
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
    const heading = page.getByRole('heading', { name: /Ủy thác điều tra|UTDT|Vụ án/i });
    await expect(heading.or(page.locator('h1, h2')).first()).toBeVisible();
  });
  test('TC-UTDT-108-E2E: [P0] List 5k UTDT p95 < 800ms', async ({ page }) => {
    // Pre: -
    // Steps: 100 GET concurrent
    // Expected: p95 < 800ms
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    const start = Date.now();
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    const elapsed = Date.now() - start;
    expect(elapsed, `Page load ${elapsed}ms phải < 5000ms`).toBeLessThan(5000);
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
  });
  test('TC-UTDT-109-E2E: [P0] utdt-stats 5k UTDT — 4 parallel computed counts < 600ms', async ({ page }) => {
    // Pre: -
    // Steps: 50 GET concurrent
    // Expected: p95 < 600ms
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    const start = Date.now();
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    const elapsed = Date.now() - start;
    expect(elapsed, `Page load ${elapsed}ms phải < 5000ms`).toBeLessThan(5000);
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
  });
  test('TC-UTDT-110-E2E: [P0] Filter computed state — query plan có index thoiHanUyThac', async ({ page }) => {
    // Pre: -
    // Steps: GET với 5k UTDT
    // Expected: < 1s, query plan dùng index
    const utdtPage = new UTDTPage(page);
    // Không wrap trong try/catch — assertion fail = test FAIL thật
    // Chỉ dùng skip khi test.skip(true) được gọi rõ ràng (e.g. loginToPage redirect về /login)
    const start = Date.now();
    await loginToPage(page, '/cases?caseType=UY_THAC_DIEU_TRA');
    const elapsed = Date.now() - start;
    expect(elapsed, `Page load ${elapsed}ms phải < 5000ms`).toBeLessThan(5000);
    expect(page.url()).toContain('/cases');
    await expect(page.locator('body')).toBeVisible();
  });

});
