name: pc02_mobile
description: PC02 Case Management Mobile App
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo-cong-an.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo-cong-an.png"
