// Ủy thác Điều tra (UTDT) — API smoke layer (Layer 1)
// Auto-generated by gen_uat_specs.py — KHÔNG sửa thủ công
import { test, expect } from '@playwright/test';

test.describe('UAT API — Ủy thác Điều tra (UTDT)', () => {

  test('TC-001-API: Tạo case UTDT hợp lệ với donViGiao + soQuyetDinhUyThac [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: POST /cases → 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-001', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-002-API: Tạo UTDT với loaiUyThac=CHUYEN_DON_NGUON_TIN [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-002', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-003-API: Tạo UTDT với loaiUyThac=UY_THAC_GIAI_QUYET [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-003', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-004-API: Tạo Delegation độc lập (workflow SCR-PF-04) [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201, delegationNumber='UT-001/2026' auto-gen
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-004', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-005-API: Delegation với relatedCaseId [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-005', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-006-API: GET /cases?caseType=UY_THAC_DIEU_TRA listing [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200, chỉ case UTDT
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-007-API: GET /cases/utdt-stats 4 trạng thái phản hồi [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: 200, body {total, byTrangThai:{DA_PHAN_HOI, KHONG_THUC_HIEN_DUOC, QUA_HAN, CHUA_
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-008-API: Filter theo trangThaiPhanHoi=QUA_HAN [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200, case có thoiHanUyThac<now
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-009-API: Filter theo donViGiao [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-010-API: Filter date range ngayTiepNhan [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-011-API: Cập nhật kết quả UTDT (ketQuaUyThac + ngayTraKetQua) [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-011', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-012-API: Cập nhật metadata utdt_lyDoKhongThucHienDuoc [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-012', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-013-API: CaseFormPage hiển thị tab ’Thông tin Ủy thác’ tại vị trí 2 [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-014-API: Row click → /uy-thac-dieu-tra/:id/edit redirect /cases/:id/edit [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Route | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-015-API: Update Delegation status PENDING → RECEIVED [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-015', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-016-API: Delegation RECEIVED → COMPLETED có completedDate [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-016', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-017-API: Soft-delete Delegation bởi creator [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delete | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-018-API: Tạo UTDT thiếu donViGiao (v0.67.3.0 bắt buộc) [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-018', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-019-API: caseProvenance=UY_THAC_DIEU_TRA nhưng caseType=REGULAR [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400/422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-019', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-020-API: loaiUyThac enum không hợp lệ [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-020', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-021-API: donViGiao > 500 ký tự [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-021', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-022-API: soQuyetDinhUyThac > 100 ký tự [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-022', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-023-API: loaiThongTin > 200 ký tự [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-023', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-024-API: thoiHanUyThac < ngayTiepNhan [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400/200 flag
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-024', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-025-API: ngayTraKetQua < ngayTiepNhan [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-025', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-026-API: Delegation thiếu receivingUnit [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-026', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-027-API: Delegation thiếu content [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-027', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-028-API: Delegation status không thuộc enum (XYZ) [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-028', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-029-API: delegationNumber manual trùng [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 409 unique
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-029', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-030-API: relatedCaseId không tồn tại [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400/404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-030', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-031-API: User Team A xem UTDT Team B (IDOR) [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-032-API: GET /delegations/X khác scope [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Delegation | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-033-API: GET không JWT [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Auth | Expected: 401
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-034-API: User không có write:Case create UTDT [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Auth | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-035-API: Delegation xóa bởi non-creator non-admin [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Delete | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-036-API: GET utdt-stats không strip caseType filter [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: 200 vẫn force UY_THAC_DIEU_TRA
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-037-API: GET utdt-stats không strip trangThaiPhanHoi [@RED @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: 200 vẫn trả 4 trạng thái
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-038-API: Filter trangThaiPhanHoi không hợp lệ [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-039-API: investigatorName search SQL injection [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200 không leak
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-040-API: Update kết quả UTDT trên case không phải UTDT [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 400/200 ignore
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-040', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-041-API: Tab ’Thông tin Ủy thác’ hiển thị khi caseProvenance khác UY_THAC_DIEU_TRA [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-042-API: Đổi caseProvenance khác → tab UTDT ẩn ngay [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-043-API: Update OCC stale [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 409
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-043', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-044-API: limit > 100 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-045-API: Sort theo donViGiao injection [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-046-API: loaiUyThac=null nhưng vẫn submit [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 400 hoặc 200 nếu optional
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-047-API: ngayTraKetQua tương lai (>now) [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400/200 cảnh báo
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-047', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-048-API: Hidden field utdt_lyDoKhongThucHienDuoc bypass [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-049-API: Stats với case caseType=REGULAR (không UTDT) — phải bỏ qua [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: GET utdt-stats chỉ count UTDT
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-050-API: Bulk assign UTDT khác đơn vị [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Bulk | Expected: 403/partial
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-050', _module: 'UTDT.Bulk' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-051-API: Đổi caseType từ UY_THAC_DIEU_TRA → REGULAR [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 400 immutable hoặc 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-051', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-052-API: Xóa UTDT case có sub-entities [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delete | Expected: 422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-053-API: Update completedDate < createdAt [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delegation | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-053', _module: 'UTDT.Delegation' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-054-API: Delete với non-creator non-admin [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delegation | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-055-API: Tạo case UTDT với linkedPetitionId (mâu thuẫn provenance) [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400 CHECK constraint
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-055', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-056-API: donViGiao = 500 (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-056', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-057-API: donViGiao = 1 ký tự (min) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-057', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-058-API: soQuyetDinhUyThac = 100 (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-058', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-059-API: loaiThongTin = 200 (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-059', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-060-API: thoiHanUyThac = now (boundary QUA_HAN) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: trangThaiPhanHoi=CHUA_PHAN_HOI hoặc QUA_HAN
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-061-API: thoiHanUyThac = now-1s (QUA_HAN) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: trangThaiPhanHoi=QUA_HAN
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-062-API: limit=100 [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-063-API: loaiUyThac 3 enum partition [@EP @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-063', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-064-API: trangThaiPhanHoi 4 enum + default [@EP @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-065-API: DelegationStatus 3 partition [@EP @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delegation | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-066-API: Delegation PENDING → RECEIVED [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-067-API: Delegation RECEIVED → COMPLETED [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-068-API: COMPLETED → bất kỳ (terminal) [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.State | Expected: 422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-069-API: trangThaiPhanHoi computed precedence DA_PHAN_HOI > KHONG_THUC_HIEN_DUOC [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.State | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-070-API: trangThaiPhanHoi precedence QUA_HAN < KHONG_THUC_HIEN_DUOC [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.State | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-071-API: Decision Table — trangThaiPhanHoi 16 combination (4 fields × 2 state) [@DECISION @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Decision | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-072-API: caseProvenance × caseType validation CHECK constraint [@DECISION @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Decision | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-073-API: SQL Injection trong donViGiao filter [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-074-API: XSS donViGiao + ketQuaUyThac [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-075-API: IDOR — GET delegation cross-user [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-076-API: Mass assignment delegationNumber để override engine [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 201 server ignore + auto-gen
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-077-API: CSRF POST cross-origin [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: CORS reject
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-078-API: Privilege escalation — non-dispatcher reassign delegation [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-079-API: Rate limit list UTDT [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 429
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([429, 200, 201]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-080-API: Token replay sau khi user.dataScope thay đổi [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: Phải áp scope mới (refresh)
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-081-API: Audit log delegation lưu actor + diff [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-082-API: donViGiao tiếng Việt có dấu [@DATA @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Data | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-083-API: Trim donViGiao leading/trailing [@DATA @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Data | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-084-API: ngayTiepNhan ISO UTC+7 [@DATA @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Data | Expected: ISO
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-085-API: metadata JSON sâu (nested objects) [@DATA @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.Data | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-086-API: Concurrent update kết quả + lý do không thực hiện [@EDGE @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Edge | Expected: 1 OK 1 409
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-086', _module: 'UTDT.Edge' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-087-API: thoiHanUyThac vượt 365 ngày [@EDGE @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Edge | Expected: 201 (no upper limit) hoặc 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-088-API: Stats khi 0 UTDT [@EDGE @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-089-API: Tab UTDT navigation bằng arrow keys [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-090-API: donViGiao field label htmlFor [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-091-API: Contrast 4 trangThaiPhanHoi badge [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-092-API: Required field ’Đơn vị giao’ có dấu * + aria-required [@A11Y @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-093-API: Error catch real-error (v0.67.3.0) đọc qua live region [@A11Y @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-094-API: Chrome 130 Win [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-095-API: Firefox 130 [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-096-API: Edge 130 [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-097-API: Safari 17 [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-098-API: Mobile 375x667 — tab UTDT scroll horizontal [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-099-API: Tablet 768x1024 [@COMPAT @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-100-API: List 1000 UTDT < 2s [@PERFORMANCE @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Perf | Expected: P95 < 2s
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-101-API: utdt-stats 4 parallel count < 1s [@PERFORMANCE @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Perf | Expected: P95 < 1s
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-102-API: Concurrent 30 create delegation [@PERFORMANCE @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.Perf | Expected: delegationNumber unique không collision
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-103-API: create delegation emit utdt.assigned → SSE assignedTo [@INTEGRATION @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Notify | Expected: SSE event
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-104-API: Case UTDT khi caseProvenance=UY_THAC_DIEU_TRA tự force caseType [@INTEGRATION @P0]', async ({ request, baseURL }) => {
    // Module: UTDT.Case | Expected: 201 caseType=UY_THAC_DIEU_TRA
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-105-API: FE list UTDT với 6 filter combine (caseType+donViGiao+loaiUyThac+date+state+investigator) [@INTEGRATION @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Filter | Expected: 200 đúng intersect
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-106-API: caseProvenance khác UY_THAC_DIEU_TRA nhưng truyền donViGiao [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400 hoặc 200 ignore
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-106', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-107-API: ngayTraKetQua set nhưng ketQuaUyThac trống [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Create | Expected: 400 (cần cả 2)
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-107', _module: 'UTDT.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-108-API: PATCH /:id/assign vào non-investigator [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 400/403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-108', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-109-API: POST /delegations content > 5000 ký tự [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delegation | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-110-API: receivingUnit > 255 ký tự [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delegation | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-111-API: investigatorName chứa wildcard SQL [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Read | Expected: 200 escape
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-112-API: Save UTDT form nhưng API throw — error visible (v0.67.3.0) [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-113-API: GET utdt-stats khi DB chỉ có case không UTDT [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Stats | Expected: 200 all 0
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases/utdt-stats`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-114-API: Delete UTDT có Delegation liên kết [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Delete | Expected: 422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-115-API: Tab UTDT click trực tiếp URL khi caseProvenance khác [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Form | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-116-API: /uy-thac-dieu-tra/:id/edit với id không tồn tại [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Route | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-117-API: Update Delegation status thẳng PENDING → COMPLETED [@RED @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Update | Expected: 422 hoặc 200 tùy spec
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-117', _module: 'UTDT.Update' },
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-118-API: Path traversal qua delegationNumber regex [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-119-API: NoSQL/Prisma operator injection trong filter [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-120-API: Sensitive PII export — donViGiao + investigator name [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-121-API: Force browse /cases/X/edit của case UTDT đơn vị khác [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.Security | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-122-API: Section UTDT có heading h2 + landmark role [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-123-API: Date picker thoiHanUyThac keyboard accessible [@A11Y @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-124-API: PWA offline xem UTDT cached [@COMPAT @P2]', async ({ request, baseURL }) => {
    // Module: UTDT.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/delegations`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });

});