// Quản lý Vụ án (Cases) — API smoke layer (Layer 1)
// Auto-generated by gen_uat_specs.py — KHÔNG sửa thủ công
import { test, expect } from '@playwright/test';

test.describe('UAT API — Quản lý Vụ án (Cases)', () => {

  test('TC-001-API: Tạo vụ án mới hợp lệ với provenance DIRECT_DISCOVERY [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: POST /api/v1/cases → 201, body có id + caseCode auto-gen
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-001', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-002-API: Tạo vụ án từ Petition (FROM_PETITION) với optimistic lock [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: POST /cases → 201; Petition.linkedCaseId được set
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-002', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-003-API: Tạo vụ án từ Incident (FROM_INCIDENT) [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201; Incident.status → DA_CHUYEN_VU_AN
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-003', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-004-API: Tạo vụ án UTDT với caseType=UY_THAC_DIEU_TRA và donViGiao [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-004', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-005-API: Liệt kê vụ án với pagination mặc định [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200, body {data:[...], total, limit:20, offset:0}
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-006-API: Filter theo status=DANG_DIEU_TRA [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200, data items.status=='DANG_DIEU_TRA'
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-007-API: Search theo tên vụ án (ILIKE) [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200, name ILIKE %trộm%
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-008-API: Cập nhật vụ án với optimistic lock đúng [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 200, body updatedAt mới
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-008', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-009-API: Chuyển status TIEP_NHAN → DANG_DIEU_TRA [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-009', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-010-API: Đặt status TAM_DINH_CHI có lyDoTamDinhChiVuAn [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-010', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-011-API: Soft-delete vụ án TIEP_NHAN bởi creator với reason [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Delete | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-012-API: ADMIN restore vụ án đã xóa [@GREEN @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Restore | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-013-API: Dispatcher gán investigator cho vụ án [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Assign | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-013', _module: 'Cases.Assign' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-014-API: Export Excel theo phường [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Export | Expected: 200, content-type xlsx
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-015-API: Bulk delete 5 vụ án [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Bulk | Expected: 200, body summary
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-016-API: Xem journey timeline của vụ án [@GREEN @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Journey | Expected: 200, events sorted desc by createdAt
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-017-API: GET /cases/stats trả về count đúng theo status [@GREEN @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Stats | Expected: 200, body {TIEP_NHAN:n1, DANG_DIEU_TRA:n2, ...}
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-018-API: Tạo case kèm 3 subjects + 2 evidences atomic [@GREEN @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Atomic | Expected: 201, body có ids của subjects/evidences
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-018', _module: 'Cases.Atomic' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-019-API: Tạo vụ án thiếu name (required) [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400, body errors.name
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-019', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-020-API: Tạo vụ án không có caseProvenance [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-020', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-021-API: FROM_PETITION nhưng thiếu linkedPetitionId [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-021', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-022-API: FROM_INCIDENT thiếu linkedIncidentId [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-022', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-023-API: UY_THAC_DIEU_TRA thiếu donViGiao (v0.67.3.0) [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-023', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-024-API: Optimistic lock conflict khi 2 user edit [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 409 Conflict
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-024', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-025-API: Đổi status sang TAM_DINH_CHI thiếu lyDoTamDinhChiVuAn [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-025', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-026-API: Non-creator non-admin xóa vụ án [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Delete | Expected: 403 Forbidden
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-027-API: Xóa vụ án không phải TIEP_NHAN [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Delete | Expected: 400/422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-028-API: Xóa vụ án còn linked Petition/Incident [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Delete | Expected: 422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-029-API: Reason xóa <10 ký tự [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Delete | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-030-API: Non-ADMIN restore [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Restore | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-030', _module: 'Cases.Restore' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-031-API: Non-dispatcher gọi assign [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Assign | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-031', _module: 'Cases.Assign' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-032-API: User ĐTV scope khác xem case không thuộc tổ [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 404 (không leak existence)
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-033-API: limit > 100 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 400 hoặc clamp về 100
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-034-API: offset âm [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-035-API: fromDate > toDate [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200 [] hoặc 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-036-API: Update tên >500 ký tự [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-036', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-037-API: Crime > 255 ký tự [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-037', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-038-API: sourceDocumentNote > 1000 ký tự [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-038', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-039-API: Subjects > 100 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-039', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-040-API: Evidences > 100 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-040', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-041-API: documentIds > 50 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-041', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-042-API: investigatorId không tồn tại [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400/404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-042', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-043-API: assignedTeamId thuộc đơn vị khác [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 403/400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-043', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-044-API: deadline trong quá khứ [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 200 + flag editedAfterWindow / hoặc 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-044', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-045-API: ngayKhoiTo định dạng sai [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-045', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-046-API: capDoToiPham không hợp lệ [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-046', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-047-API: loaiUyThac không thuộc enum [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-047', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-048-API: Truy cập không JWT [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Auth | Expected: 401
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-049-API: JWT hết hạn [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Auth | Expected: 401
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-050-API: JWT chữ ký sai [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Auth | Expected: 401
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-051-API: Pre-migration createdById=NULL chỉ ADMIN xóa [@RED @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-052-API: sortBy với cột không tồn tại [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 400 hoặc fallback createdAt
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-053-API: trangThaiPhanHoi không hợp lệ [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-054-API: Update vụ án đã soft-delete [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-054', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-055-API: Bulk assign với ids khác đơn vị [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Bulk | Expected: 403 hoặc partial result
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-055', _module: 'Cases.Bulk' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-056-API: Bulk delete > 100 items [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Bulk | Expected: 400 hoặc throttle 5 req/min
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-057-API: Export vượt rate limit 5/min [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Export | Expected: 429 Too Many Requests
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([429, 200, 201]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-058-API: linkedPetitionId thuộc Petition đã linked case khác [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 409/422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-058', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-059-API: linkedIncidentId đã được dùng (@unique) [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 409
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-059', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-060-API: Đổi caseProvenance sau khi tạo [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 422 immutable hoặc cho phép
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-060', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-061-API: name = 500 ký tự (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-061', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-062-API: name = 499 ký tự (max-1) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-062', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-063-API: name = 1 ký tự (min) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-063', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-064-API: limit=100 (max) [@BOUNDARY @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-065-API: limit=1 (min) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-066-API: reason xóa = 10 ký tự (min) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-066', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-067-API: reason xóa = 500 ký tự (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-067', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-068-API: subjects = 100 (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-068', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-069-API: evidences = 100 (max) [@BOUNDARY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-069', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-070-API: offset=0 (min) [@BOUNDARY @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-071-API: caseProvenance hợp lệ — partition cho mỗi giá trị 8 enum [@EP @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-071', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-072-API: status enum 10 giá trị filter ra đúng partition [@EP @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200 data đúng
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-073-API: capDoToiPham 4 partition [@EP @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-074-API: sortOrder asc / desc [@EP @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200 thứ tự đúng
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-075-API: overdue=true vs false [@EP @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200 filter đúng deadline<now
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-076-API: DANG_DIEU_TRA → DA_KET_LUAN [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-077-API: DA_KET_LUAN → DANG_TRUY_TO [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-078-API: DANG_TRUY_TO → DANG_XET_XU [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-079-API: TAM_DINH_CHI → DA_KET_LUAN (phục hồi) [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-080-API: DINH_CHI là terminal [@STATE @P0]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 422
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-081-API: soLanTamDinhChi auto-increment khi vào TĐC lần 2 [@STATE @P1]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-082-API: DA_LUU_TRU không cho edit field nghiệp vụ [@STATE @P2]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 422 hoặc 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([422, 400]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-083-API: CaseStatusHistory ghi cả from + to + changedBy [@STATE @P1]', async ({ request, baseURL }) => {
    // Module: Cases.State | Expected: 200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-084-API: Decision Table — trangThaiPhanHoi 4 case [@DECISION @P0]', async ({ request, baseURL }) => {
    // Module: Cases.UTDT | Expected: GET /cases/utdt-stats trả count đúng
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-085-API: Decision Table — lyDoTamDinhChiVuAn cần khi status=TAM_DINH_CHI [@DECISION @P0]', async ({ request, baseURL }) => {
    // Module: Cases.TDC | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-086-API: SQL Injection trong search [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 200 (parametrized), không leak data
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-087-API: XSS trong name vụ án [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-088-API: IDOR — đoán id case khác đơn vị [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 404 không leak
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-089-API: Mass assignment — gửi createdById trong body [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 201 nhưng createdById = actor thật
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-090-API: CSRF — POST không token [@SECURITY @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 403 (CORS hoặc CSRF guard)
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-091-API: Path traversal trong filename export [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 400/sanitize
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-092-API: NoSQL/Prisma injection trong sortBy [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 400 whitelist
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-093-API: Rate limit brute force list endpoint [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 429
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([429, 200, 201]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-094-API: Auth missing trên restore admin endpoint [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 401
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      
      data: { _tc: 'TC-094', _module: 'Cases.Security' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-095-API: Sensitive data exposure trong audit log API [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: Không trả password/token/raw IP
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-096-API: CORS — origin trái phép bị reject [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: CORS reject
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-097-API: JWT replay sau logout [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 401 (nếu blacklist) hoặc 200 (nếu stateless)
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      
      
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-098-API: Tên vụ án Unicode đa byte (tiếng Việt + emoji) [@DATA @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Data | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-099-API: Trim leading/trailing space [@DATA @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Data | Expected: 201 với name='Vụ A'
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-100-API: Null byte injection [@DATA @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Data | Expected: 400 hoặc strip
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-101-API: Date ISO8601 timezone VN (UTC+7) [@DATA @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Data | Expected: 201
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-102-API: Number overflow soLanTamDinhChi [@DATA @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Data | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-103-API: Tạo 2 case song song cùng linkedIncidentId [@EDGE @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 1 thành công 201, 1 409 unique
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-103', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-104-API: Subjects/Evidences trùng code trong 1 case [@EDGE @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-104', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-105-API: Stats khi DB rỗng (0 case) [@EDGE @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Stats | Expected: 200, mọi key = 0
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-106-API: Tab key di chuyển focus qua mọi field form [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-107-API: Label gắn đúng với input (htmlFor) [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-108-API: Contrast badge status ≥ 4.5:1 [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-109-API: Error message announce qua aria-live [@A11Y @P2]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-110-API: Skip link đến nội dung chính [@A11Y @P2]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-111-API: Chrome 130+ Windows [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-112-API: Firefox 130+ macOS [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-113-API: Edge 130+ [@COMPAT @P2]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-114-API: Safari 17+ [@COMPAT @P2]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-115-API: Mobile portrait 375x667 (iPhone SE) [@COMPAT @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-116-API: Tablet 768x1024 [@COMPAT @P2]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-117-API: GET /cases list 1000 record < 2s [@PERFORMANCE @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Perf | Expected: P95 < 2000ms
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-118-API: POST tạo case kèm 100 subjects + 100 evidences < 5s [@PERFORMANCE @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Perf | Expected: < 5s
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-118', _module: 'Cases.Perf' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-119-API: 50 concurrent GET /cases/stats không sập [@PERFORMANCE @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Perf | Expected: Error rate < 1%, P95 < 1s
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-120-API: Export 5000 case không OOM [@PERFORMANCE @P2]', async ({ request, baseURL }) => {
    // Module: Cases.Perf | Expected: 200, file < 50MB
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-121-API: Tạo case assigned → SSE/push tới investigator [@INTEGRATION @P0]', async ({ request, baseURL }) => {
    // Module: Cases.Notify | Expected: SSE event CASE_ASSIGNED
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-121', _module: 'Cases.Notify' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-122-API: Generate caseCode auto khi tạo [@INTEGRATION @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Doc | Expected: caseCode != null
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-122', _module: 'Cases.Doc' },
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-123-API: Tạo case với metadata vượt 64KB JSON [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 413/400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-123', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-124-API: caseProvenance=FROM_PETITION với linkedPetitionId không tồn tại [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400/404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-124', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-125-API: linkedPetitionId thuộc Petition đã soft-delete [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-125', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-126-API: linkedIncidentId thuộc Incident đã soft-delete [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-126', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-127-API: Update của user khác đơn vị [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-127', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([404, 403]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-128-API: Stats vụ án không trong scope [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200 chỉ count case thuộc Team A
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-129-API: Subject thiếu fullName trong atomic create [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Atomic | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-130-API: Evidence thiếu code [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Atomic | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-131-API: documentIds chứa id không tồn tại [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Atomic | Expected: 400/404
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-132-API: TĐC backfill bởi non-creator non-admin [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Update | Expected: 403
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.put(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-132', _module: 'Cases.Update' },
      failOnStatusCode: false,
    });
    expect([401, 403, 404]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-133-API: Journey với page=-1 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-134-API: limit journey > 200 [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 400/clamp
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-135-API: sourceDocumentNote điền khi caseProvenance=FROM_PETITION [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400 hoặc ignore
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-135', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-136-API: Bulk export với ids rỗng [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Bulk | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-136', _module: 'Cases.Bulk' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-137-API: ngayTraKetQua < ngayTiepNhan [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UTDT | Expected: 400/200
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-138-API: XXE trong upload XML metadata [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 400 hoặc strip entity
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });


  test('TC-139-API: SSRF qua URL field trong notes [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 201, server không fetch URL
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-140-API: Privilege escalation — đổi role qua body [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: 201, role không đổi
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-141-API: HTTP method tampering DELETE qua POST _method [@SECURITY @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Security | Expected: Không xóa
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-142-API: Form error message screen reader đọc được [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-143-API: Keyboard ESC đóng dialog confirm delete [@A11Y @P1]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.delete(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-144-API: Icon-only button có aria-label [@A11Y @P2]', async ({ request, baseURL }) => {
    // Module: Cases.UI | Expected: 
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-145-API: Pagination total > tổng thật do scope leak [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: total === count thuộc scope
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-146-API: Search SQL keyword reserved [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Read | Expected: 200 không exception
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.get(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      
      failOnStatusCode: false,
    });
    expect([200, 201, 400, 401, 403, 404, 409, 422]).toContain(response.status());
    expect(response.headers()).toBeTruthy();
  });


  test('TC-147-API: loaiThongTin > 200 ký tự [@RED @P1]', async ({ request, baseURL }) => {
    // Module: Cases.Create | Expected: 400
    const url = `${baseURL ?? 'http://localhost:3000'}/api/v1/cases`;
    const response = await request.post(url, {
      headers: { Authorization: `Bearer ${process.env.UAT_TOKEN || 'mock-token'}` },
      data: { _tc: 'TC-147', _module: 'Cases.Create' },
      failOnStatusCode: false,
    });
    expect(response.status()).toBeGreaterThanOrEqual(400);
    expect(response.headers()).toBeTruthy();
  });

});