export const petitionSearchCases = [
  { key: 'stt', query: '987654' },
  { key: 'sttCu', query: 'old987654' },
  { key: 'loaiThongTin', query: 'searchtype' },
  { key: 'nguonDon', query: 'searchsource' },
  { key: 'nguoiGui', query: 'searchsender' },
  { key: 'tomTat', query: 'searchsummary' },
  { key: 'donViGiaiQuyet', query: 'searchunit' },
  { key: 'ketQuaXuLyKhac', query: 'searchresult' },
  { key: 'nguoiNhap', query: 'timkiem' },
  { key: 'trangThai', query: 'moi tiep nhan' },
  { key: 'doiTuong', query: 'searchsuspect' },
  { key: 'hanXuLy', query: '12/02/2030' },
  { key: 'ngayTao', query: '13/03/2020' },
  { key: 'ngayDeXuat', query: '14/04/2026' },
  { key: 'ngayTiepNhan', query: '11/01/2026' },
  { key: 'ngayTiepNhanNguonTin', query: '15/05/2026' },
  { key: 'ngayVietDon', query: '16/06/2026' },
  { key: 'ngayGiaoDonViGiaiQuyet', query: '17/07/2026' },
  { key: 'ngayPhieuChuyen', query: '18/08/2026' },
  { key: 'ngayCapCCCD', query: '19/09/2026' },
  { key: 'ngayVietDonChu', query: 'sau tet searchdate' },
] as const;
