/**
 * Permission resource and action keys.
 *
 * Currently mock (all-permissive). When backend implements CASL, replace
 * MOCK_ALL_PERMISSIONS with a fetch from /api/v1/auth/me (which includes
 * a `permissions` field). The string values here must match backend CASL
 * subject names exactly.
 */
export const PERMISSION_RESOURCE = {
  CASES: 'cases',
  PETITIONS: 'petitions',
  INCIDENTS: 'incidents',
  OBJECTS: 'objects',
  USERS: 'users',
  SETTINGS: 'settings',
  LAWYERS: 'lawyers',
  DIRECTORIES: 'directories',
  REPORTS: 'reports',
  CALENDAR: 'calendar',
} as const;

export type PermissionResource =
  (typeof PERMISSION_RESOURCE)[keyof typeof PERMISSION_RESOURCE];

export const PERMISSION_ACTION = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
} as const;

export type PermissionAction =
  (typeof PERMISSION_ACTION)[keyof typeof PERMISSION_ACTION];

/**
 * Full-access mock — every resource gets every action.
 * Replace with per-user API fetch when CASL is implemented.
 */
export const MOCK_ALL_PERMISSIONS: Partial<
  Record<PermissionResource, PermissionAction[]>
> = {
  [PERMISSION_RESOURCE.CASES]:       [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.PETITIONS]:   [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.INCIDENTS]:   [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.OBJECTS]:     [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.USERS]:       [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.SETTINGS]:    [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.LAWYERS]:     [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.DIRECTORIES]: [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
  [PERMISSION_RESOURCE.REPORTS]:     [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE],
  [PERMISSION_RESOURCE.CALENDAR]:    [PERMISSION_ACTION.VIEW, PERMISSION_ACTION.CREATE, PERMISSION_ACTION.EDIT, PERMISSION_ACTION.DELETE],
};
