// Generated from the frozen CG01 inventory. Verified by case-canonical-fields.spec.ts.
export const CASE_CANONICAL_FIELD_REGISTRY = [
  {
    key: 'baoCaoBanGiamDoc',
    column: 'baoCaoBanGiamDocText',
    kind: 'text',
    type: 'String?',
    labels: ['Trường hợp báo cáo Ban Giám đốc'],
  },
  {
    key: 'canCuKhongKhoiTo',
    column: 'canCuKhongKhoiTo',
    kind: 'text',
    type: 'String?',
    labels: ['Căn cứ để ra Quyết định Không khởi tố'],
  },
  {
    key: 'canCuPhucHoiVuAn',
    column: 'canCuPhucHoiVuAn',
    kind: 'text',
    type: 'String?',
    labels: ['Căn cứ ra quyết định Phục hồi điều tra vụ án'],
  },
  {
    key: 'canCuTamDinhChiNguonTin',
    column: 'canCuTamDinhChiNguonTin',
    kind: 'text',
    type: 'String?',
    labels: ['Căn cứ Tạm đình chỉ nguồn tin'],
  },
  {
    key: 'canCuTamDinhChiVuAn',
    column: 'canCuTamDinhChiVuAn',
    kind: 'text',
    type: 'String?',
    labels: ['Căn cứ tạm đình chỉ vụ án'],
  },
  {
    key: 'capDoToiPham',
    column: 'capDoToiPham',
    kind: 'select',
    type: 'CapDoToiPham?',
    labels: [
      'Phân loại tội phạm (Chỉ xác định sau khi có Quyết định khởi tố vụ án)',
    ],
  },
  {
    key: 'cccdCungCap',
    column: 'cccdCungCap',
    kind: 'text',
    type: 'String?',
    labels: ['Số căn cước công dân'],
  },
  {
    key: 'chuyenVuAnChoCQK',
    column: 'chuyenVuAnChoCQK',
    kind: 'text',
    type: 'String?',
    labels: ['Đã chuyển vụ án cho CQĐT khác'],
  },
  {
    key: 'chuyenVuViecDonViKhac',
    column: 'chuyenVuViecDonViKhac',
    kind: 'text',
    type: 'String?',
    labels: ['Chuyển vụ việc cho đơn vị khác'],
  },
  {
    key: 'crimeChinhId',
    column: 'crimeChinhId',
    kind: 'crime',
    type: 'String?',
    labels: ['Tội danh chính - BLHS 2015 (nhận định ban đầu)'],
  },
  {
    key: 'description',
    column: 'moTaChiTiet',
    kind: 'textarea',
    type: 'String?',
    labels: ['Tóm tắt nội dung'],
  },
  {
    key: 'diaChiCungCap',
    column: 'diaChiCungCap',
    kind: 'text',
    type: 'String?',
    labels: ['Địa chỉ cá nhân, cơ quan, tổ chức cung cấp, bị hại'],
  },
  {
    key: 'dieuTraVienText',
    column: 'dieuTraVien',
    kind: 'text',
    type: 'String?',
    labels: ['Điều tra viên thụ lý'],
  },
  {
    key: 'doVatTaiLieuKemTheo',
    column: 'doVatTaiLieuKemTheo',
    kind: 'textarea',
    type: 'String?',
    labels: ['Đồ vật, tài liệu kèm theo'],
  },
  {
    key: 'ghiChuKhac',
    column: 'ghiChuKhac',
    kind: 'textarea',
    type: 'String?',
    labels: ['Ghi chú khác'],
  },
  {
    key: 'ghiChuNhapHoSo',
    column: 'ghiChuNhapHoSo',
    kind: 'textarea',
    type: 'String?',
    labels: ['Ghi chú nhập vào hồ sơ nào'],
  },
  {
    key: 'ghiChuTrungDon',
    column: 'ghiChuTrungDon',
    kind: 'text',
    type: 'String?',
    labels: ['Ghi chú trùng đơn'],
  },
  {
    key: 'ketQuaXuLyKhac',
    column: 'ketQuaXuLyKhac',
    kind: 'textarea',
    type: 'String?',
    labels: ['Kết quả xử lý, giải quyết khác'],
  },
  {
    key: 'khacPhucLyDoTDCVuViec',
    column: 'khacPhucLyDoTDCVuViec',
    kind: 'textarea',
    type: 'String?',
    labels: ['Biên bản, báo cáo, kế hoạch khắc phục lý do TĐC vụ việc'],
  },
  {
    key: 'laCongNgheCao',
    column: 'laCongNgheCao',
    kind: 'toggle',
    type: 'Boolean',
    labels: ['Bấm chọn nếu xác định đây là tội phạm công nghệ cao'],
  },
  {
    key: 'lanhDaoToTung',
    column: 'lanhDaoToTung',
    kind: 'text',
    type: 'String?',
    labels: ['Lãnh đạo phụ trách tố tụng'],
  },
  {
    key: 'lenhNhapKho',
    column: 'lenhNhapKho',
    kind: 'text',
    type: 'String?',
    labels: ['Lệnh nhập, phiếu nhập kho'],
  },
  {
    key: 'loaiThongTin',
    column: 'loaiThongTin',
    kind: 'text',
    type: 'String?',
    labels: ['Loại thông tin'],
  },
  {
    key: 'lyDoKhongKhoiTo',
    column: 'lyDoKhongKhoiTo',
    kind: 'multiselect',
    type: 'String[]',
    labels: ['Lý do ra Quyết định không khởi tố vụ án'],
  },
  {
    key: 'lyDoTamDinhChiNguonTin',
    column: 'lyDoTamDinhChiNguonTin',
    kind: 'multiselect',
    type: 'String[]',
    labels: ['Lý do tạm đình chỉ'],
  },
  {
    key: 'lyDoTamDinhChiVuAn',
    column: 'lyDoTamDinhChiVuAn',
    kind: 'multiselect',
    type: 'LyDoTamDinhChiVuAn[]',
    labels: ['Lý do tạm đình chỉ vụ án'],
  },
  {
    key: 'ngayBanAnCoHieuLuc',
    column: 'ngayBanAnCoHieuLuc',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày tháng năm bản án của toà án có hiệu lực'],
  },
  {
    key: 'ngayCapCccd',
    column: 'ngayCapCccd',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày cấp CCCD'],
  },
  {
    key: 'ngayDeXuat',
    column: 'ngayDeXuat',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày/Tháng/Năm đề xuất'],
  },
  {
    key: 'ngayDinhChiVuAn',
    column: 'ngayDinhChiVuAn',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Quyết định đình chỉ vụ án'],
  },
  {
    key: 'ngayGiaoDonViGiaiQuyet',
    column: 'ngayGiaoDonViGiaiQuyet',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày giao đơn vị giải quyết'],
  },
  {
    key: 'ngayHetThoiHieu',
    column: 'ngayHetThoiHieu',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày hết thời hiệu truy cứu TNHS vụ án'],
  },
  {
    key: 'ngayHetThoiHieuVuViec',
    column: 'ngayHetThoiHieuVuViec',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày tháng năm hết thời hiệu truy cứu TNHS'],
  },
  {
    key: 'ngayKhoiTo',
    column: 'ngayKhoiTo',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày ra Quyết định Khởi tố vụ án'],
  },
  {
    key: 'ngayKLDT',
    column: 'ngayKLDT',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Kết luận điều tra vụ án'],
  },
  {
    key: 'ngayNhapVuAn',
    column: 'ngayNhapVuAn',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày tháng năm nhập vụ án'],
  },
  {
    key: 'ngayPhieuChuyen',
    column: 'ngayPhieuChuyen',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày phiếu chuyển/ Công văn/ Ủy thác điều tra'],
  },
  {
    key: 'ngayPhucHoi',
    column: 'ngayPhucHoi',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Quyết định phục hồi điều tra vụ án'],
  },
  {
    key: 'ngayPhucHoiNguonTin',
    column: 'ngayPhucHoiNguonTin',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Phục hồi nguồn tin tội phạm'],
  },
  {
    key: 'ngayQDDieuTraLai',
    column: 'ngayQDDieuTraLai',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Quyết định điều tra lại'],
  },
  {
    key: 'ngayQDKhongKhoiTo',
    column: 'ngayQDKhongKhoiTo',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày ra Quyết định Không khởi tố'],
  },
  {
    key: 'ngayQDPhanCongNguonTin',
    column: 'ngayQDPhanCongNguonTin',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày ra Quyết định phân công giải quyết nguồn tin tội phạm'],
  },
  {
    key: 'ngayQDTamDinhChiNguonTin',
    column: 'ngayQDTamDinhChiNguonTin',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày ra Quyết định Tạm đình chỉ nguồn tin'],
  },
  {
    key: 'ngayTachHanhVi',
    column: 'ngayTachHanhVi',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Quyết định tách hành vi'],
  },
  {
    key: 'ngayTachVuAn',
    column: 'ngayTachVuAn',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Quyết định tách hồ sơ'],
  },
  {
    key: 'ngayTamDinhChi',
    column: 'ngayTamDinhChi',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày Quyết định tạm đình chỉ vụ án'],
  },
  {
    key: 'ngayTiepNhanNguonTin',
    column: 'ngayTiepNhan',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày tiếp nhận (theo biên bản tiếp nhận nguồn tin)'],
  },
  {
    key: 'ngayVietDon',
    column: 'ngayVietDon',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày viết đơn'],
  },
  {
    key: 'ngayXayRa',
    column: 'ngayXayRa',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Ngày tội phạm xảy ra'],
  },
  {
    key: 'nghiVanDoiTuong',
    column: 'nghiVanDoiTuong',
    kind: 'text',
    type: 'String?',
    labels: ['Nghi vấn đối tượng hoặc bị can'],
  },
  {
    key: 'nguonDon',
    column: 'nguonDon',
    kind: 'text',
    type: 'String?',
    labels: ['Nguồn đơn/Đơn vị giao'],
  },
  {
    key: 'nhanXet',
    column: 'nhanXet',
    kind: 'textarea',
    type: 'String?',
    labels: ['Nhận xét'],
  },
  {
    key: 'nhapVaoVuViecSo',
    column: 'nhapVaoVuViecSo',
    kind: 'text',
    type: 'String?',
    labels: ['Nhập vào vụ việc hồ sơ khác'],
  },
  {
    key: 'noiCapCccd',
    column: 'noiCapCccd',
    kind: 'text',
    type: 'String?',
    labels: ['Nơi cấp CCCD'],
  },
  {
    key: 'noiLuuTruBaoQuan',
    column: 'noiLuuTruBaoQuan',
    kind: 'text',
    type: 'String?',
    labels: ['Nơi lưu trữ, bảo quản, kê biên, phong tỏa'],
  },
  {
    key: 'noiXayRa',
    column: 'noiXayRa',
    kind: 'text',
    type: 'String?',
    labels: ['Nơi xảy ra tội phạm'],
  },
  {
    key: 'noiXayRaPhuongXa',
    column: 'noiXayRaPhuongXa',
    kind: 'text',
    type: 'String?',
    labels: ['Nơi xảy ra (cấp phường/xã)'],
  },
  {
    key: 'phanLoaiDanSu',
    column: 'phanLoaiDanSu',
    kind: 'text',
    type: 'String?',
    labels: ['Phân loại dân sự'],
  },
  {
    key: 'phanLoaiNguonTinBanDau',
    column: 'phanLoaiNguonTinBanDau',
    kind: 'select',
    type: 'String?',
    labels: ['Phân loại ban đầu'],
  },
  {
    key: 'phuongThucThuDoan',
    column: 'phuongThucThuDoan',
    kind: 'text',
    type: 'String?',
    labels: ['Phương thức thủ đoạn'],
  },
  {
    key: 'sdtCungCap',
    column: 'sdtCungCap',
    kind: 'text',
    type: 'String?',
    labels: ['Số điện thoại nguyên đơn'],
  },
  {
    key: 'sinhNamCungCap',
    column: 'sinhNamCungCap',
    kind: 'text',
    type: 'String?',
    labels: ['Sinh năm'],
  },
  {
    key: 'soBanAnCoHieuLuc',
    column: 'soBanAnCoHieuLuc',
    kind: 'text',
    type: 'String?',
    labels: ['Số bản án của toà án có hiệu lực'],
  },
  {
    key: 'soKLDT',
    column: 'soKLDT',
    kind: 'text',
    type: 'String?',
    labels: ['Số KLĐT đề nghị truy tố'],
  },
  {
    key: 'soPhieuChuyen',
    column: 'soPhieuChuyen',
    kind: 'text',
    type: 'String?',
    labels: ['Số phiếu chuyển/ Công văn/ Ủy thác điều tra'],
  },
  {
    key: 'soPhucHoiNguonTin',
    column: 'soPhucHoiNguonTin',
    kind: 'text',
    type: 'String?',
    labels: ['Số Phục hồi nguồn tin tội phạm'],
  },
  {
    key: 'soQDDieuTraLai',
    column: 'soQDDieuTraLai',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định điều tra lại'],
  },
  {
    key: 'soQDDinhChiVuAn',
    column: 'soQDDinhChiVuAn',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định đình chỉ vụ án'],
  },
  {
    key: 'soQDKhongKhoiTo',
    column: 'soQDKhongKhoiTo',
    kind: 'text',
    type: 'String?',
    labels: ['Quyết định Không khởi tố'],
  },
  {
    key: 'soQDNhapVuAn',
    column: 'soQDNhapVuAn',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định nhập vụ án'],
  },
  {
    key: 'soQDPhanCongNguonTin',
    column: 'soQDPhanCongNguonTin',
    kind: 'text',
    type: 'String?',
    labels: ['Quyết định phân công giải quyết nguồn tin tội phạm'],
  },
  {
    key: 'soQDTachHanhVi',
    column: 'soQDTachHanhVi',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định tách hành vi'],
  },
  {
    key: 'soQDTachVuAn',
    column: 'soQDTachVuAn',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định tách vụ án'],
  },
  {
    key: 'soQDTamDinhChiNguonTin',
    column: 'soQDTamDinhChiNguonTin',
    kind: 'text',
    type: 'String?',
    labels: ['Quyết định Tạm đình chỉ nguồn tin'],
  },
  {
    key: 'soQuyetDinhKhoiTo',
    column: 'soQuyetDinhKhoiTo',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định Khởi tố vụ án'],
  },
  {
    key: 'soQuyetDinhPhucHoi',
    column: 'soQuyetDinhPhucHoi',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định Phục hồi Vụ án'],
  },
  {
    key: 'soQuyetDinhTamDinhChi',
    column: 'soQuyetDinhTamDinhChi',
    kind: 'text',
    type: 'String?',
    labels: ['Số Quyết định Tạm đình chỉ vụ án'],
  },
  {
    key: 'statistic.coBangNhom',
    column: 'statistic.coBangNhom',
    kind: 'toggle',
    type: 'toggle',
    labels: ['Xác nhận có băng nhóm'],
  },
  {
    key: 'statistic.coGhiAmGhiHinh',
    column: 'statistic.coGhiAmGhiHinh',
    kind: 'toggle',
    type: 'toggle',
    labels: ['Bấm xác nhận nếu là nguồn tin có sử dụng Ghi âm, Ghi hình'],
  },
  {
    key: 'statistic.coSuDungKQGhiAmTrongXetXu',
    column: 'statistic.coSuDungKQGhiAmTrongXetXu',
    kind: 'toggle',
    type: 'toggle',
    labels: [
      'Xác nhận trong đó: Vụ án có sử dụng kết quả Ghi âm ghi hình trong xét xử',
    ],
  },
  {
    key: 'statistic.coVPHC',
    column: 'statistic.coVPHC',
    kind: 'toggle',
    type: 'toggle',
    labels: ['Xác nhận vụ việc có vi phạm hành chính'],
  },
  {
    key: 'statistic.dieuTraMoRong',
    column: 'statistic.dieuTraMoRong',
    kind: 'number',
    type: 'number',
    labels: ['Điều tra mở rộng'],
  },
  {
    key: 'statistic.donViBaoQuanHoSo',
    column: 'statistic.donViBaoQuanHoSo',
    kind: 'text',
    type: 'text',
    labels: ['Đơn vị lưu giữ, bảo quản hồ sơ'],
  },
  {
    key: 'statistic.ghiAmGhiHinhDaDuocXetXu',
    column: 'statistic.ghiAmGhiHinhDaDuocXetXu',
    kind: 'toggle',
    type: 'toggle',
    labels: [
      'Xác nhận Trong đó: Số vụ án tiến hành Ghi âm, Ghi hình đã được xét xử',
    ],
  },
  {
    key: 'statistic.hoSoLuu',
    column: 'statistic.hoSoLuu',
    kind: 'text',
    type: 'text',
    labels: ['Số hồ sơ lưu'],
  },
  {
    key: 'statistic.khongGAGHNhungToaYeuCau',
    column: 'statistic.khongGAGHNhungToaYeuCau',
    kind: 'toggle',
    type: 'toggle',
    labels: [
      'Xác nhận trong đó: Vụ án không ghi âm ghi hình nhưng Tòa án yêu cầu cung cấp ghi âm ghi hình',
    ],
  },
  {
    key: 'statistic.laVuAnGhiAmGhiHinh',
    column: 'statistic.laVuAnGhiAmGhiHinh',
    kind: 'toggle',
    type: 'toggle',
    labels: ['Xác nhận nếu là Vụ án có sử dụng Ghi âm, Ghi hình'],
  },
  {
    key: 'statistic.ngayBatKhanCap',
    column: 'statistic.ngayBatKhanCap',
    kind: 'date',
    type: 'date',
    labels: ['Ngày Người phạm tội bị giữ trong các trường hợp khẩn cấp'],
  },
  {
    key: 'statistic.ngayDangKyHoSo',
    column: 'statistic.ngayDangKyHoSo',
    kind: 'date',
    type: 'date',
    labels: ['Ngày đăng ký hồ sơ nghiệp vụ'],
  },
  {
    key: 'statistic.ngayDauThu',
    column: 'statistic.ngayDauThu',
    kind: 'date',
    type: 'date',
    labels: ['Ngày người phạm tội đầu thú, tự thú'],
  },
  {
    key: 'statistic.ngayNopLuuHoSo',
    column: 'statistic.ngayNopLuuHoSo',
    kind: 'date',
    type: 'date',
    labels: ['Ngày nộp lưu hồ sơ'],
  },
  {
    key: 'statistic.ngayPhamToiQuaTang',
    column: 'statistic.ngayPhamToiQuaTang',
    kind: 'date',
    type: 'date',
    labels: ['Ngày người phạm tội bị bắt quả tang'],
  },
  {
    key: 'statistic.ngayPhanCongGiaiQuyetToGiac',
    column: 'statistic.ngayPhanCongGiaiQuyetToGiac',
    kind: 'date',
    type: 'date',
    labels: ['Ngày Thời điểm phân công giải quyết tố giác, tin báo'],
  },
  {
    key: 'statistic.ngayPhatHienDauHieu',
    column: 'statistic.ngayPhatHienDauHieu',
    kind: 'date',
    type: 'date',
    labels: ['Ngày CQCSĐT trực tiếp phát hiện có dấu hiệu tội phạm'],
  },
  {
    key: 'statistic.ngayThongKe',
    column: 'statistic.ngayThongKe',
    kind: 'date',
    type: 'date',
    labels: ['Ngày tổng hợp thống kê'],
  },
  {
    key: 'statistic.ngayTiepNhanTin',
    column: 'statistic.ngayTiepNhanTin',
    kind: 'date',
    type: 'date',
    labels: ['Ngày tiếp nhận tin khi đơn vị nhận được'],
  },
  {
    key: 'statistic.soBangNhomBatDuoc',
    column: 'statistic.soBangNhomBatDuoc',
    kind: 'number',
    type: 'number',
    labels: ['Bắt được bao nhiêu băng nhóm'],
  },
  {
    key: 'statistic.soBiCanCoGhiAm',
    column: 'statistic.soBiCanCoGhiAm',
    kind: 'number',
    type: 'number',
    labels: ['Số lượng bị can có ghi âm ghi hình'],
  },
  {
    key: 'statistic.soBiCanVksYeuCauGhiAm',
    column: 'statistic.soBiCanVksYeuCauGhiAm',
    kind: 'number',
    type: 'number',
    labels: ['Số lượng bị can VKS yêu cầu ghi âm ghi hình'],
  },
  {
    key: 'statistic.soBienBanGhiLoiKhaiCoGhiAm',
    column: 'statistic.soBienBanGhiLoiKhaiCoGhiAm',
    kind: 'number',
    type: 'number',
    labels: ['Số lượng biên bản ghi lời khai có ghi âm ghi hình'],
  },
  {
    key: 'statistic.soDangKyHoSo',
    column: 'statistic.soDangKyHoSo',
    kind: 'text',
    type: 'text',
    labels: ['Số đăng ký hồ sơ nghiệp vụ'],
  },
  {
    key: 'statistic.soDoiTuong',
    column: 'statistic.soDoiTuong',
    kind: 'number',
    type: 'number',
    labels: ['Số đối tượng phạm tội'],
  },
  {
    key: 'statistic.soDoiTuongBiBatVuAnKhac',
    column: 'statistic.soDoiTuongBiBatVuAnKhac',
    kind: 'number',
    type: 'number',
    labels: ['Số đối tượng bị bắt trong vụ án khác'],
  },
  {
    key: 'statistic.soDoiTuongDaBat',
    column: 'statistic.soDoiTuongDaBat',
    kind: 'number',
    type: 'number',
    labels: ['Số đối tượng bắt được'],
  },
  {
    key: 'statistic.soDoiTuongSuuTraHiemNghi',
    column: 'statistic.soDoiTuongSuuTraHiemNghi',
    kind: 'number',
    type: 'number',
    labels: ['Số đối tượng sưu tra/hiềm nghi'],
  },
  {
    key: 'statistic.soDoiTuongVPHC',
    column: 'statistic.soDoiTuongVPHC',
    kind: 'number',
    type: 'number',
    labels: ['Số đối tượng vi phạm hành chính'],
  },
  {
    key: 'statistic.soLuongBiHai',
    column: 'statistic.soLuongBiHai',
    kind: 'number',
    type: 'number',
    labels: ['Số lượng người bị hại'],
  },
  {
    key: 'statistic.soLuongNguoiChet',
    column: 'statistic.soLuongNguoiChet',
    kind: 'number',
    type: 'number',
    labels: ['Số người chết'],
  },
  {
    key: 'statistic.soNguoiBiPhatTien',
    column: 'statistic.soNguoiBiPhatTien',
    kind: 'number',
    type: 'number',
    labels: ['Số người bị phạt tiền'],
  },
  {
    key: 'statistic.soNguoiBiThuong',
    column: 'statistic.soNguoiBiThuong',
    kind: 'number',
    type: 'number',
    labels: ['Số người bị thương'],
  },
  {
    key: 'statistic.soSungThuHoi',
    column: 'statistic.soSungThuHoi',
    kind: 'number',
    type: 'number',
    labels: ['Số lượng súng thu hồi'],
  },
  {
    key: 'statistic.soThuocNoThuHoi',
    column: 'statistic.soThuocNoThuHoi',
    kind: 'number',
    type: 'number',
    labels: ['Số lượng thuốc nổ thu hồi'],
  },
  {
    key: 'statistic.soTienBiThietHai',
    column: 'statistic.soTienBiThietHai',
    kind: 'number',
    type: 'number',
    labels: ['Số tiền bị thiệt hại (triệu Việt nam Đồng)'],
  },
  {
    key: 'statistic.soTienThuHoi',
    column: 'statistic.soTienThuHoi',
    kind: 'number',
    type: 'number',
    labels: ['Số tiền thu hồi được (triệu Việt Nam Đồng)'],
  },
  {
    key: 'statistic.suDungVuKhiNong',
    column: 'statistic.suDungVuKhiNong',
    kind: 'text',
    type: 'text',
    labels: ['Sử dụng vũ khí nóng'],
  },
  {
    key: 'statistic.tongSoBienBanGhiLoiKhai',
    column: 'statistic.tongSoBienBanGhiLoiKhai',
    kind: 'number',
    type: 'number',
    labels: ['Tổng số biên bản ghi lời khai'],
  },
  {
    key: 'statistic.tongSoBienBanHoiCung',
    column: 'statistic.tongSoBienBanHoiCung',
    kind: 'number',
    type: 'number',
    labels: ['Tổng số biên bản hỏi cung bị can'],
  },
  {
    key: 'statistic.tongSoBienBanHoiCungCoGhiAm',
    column: 'statistic.tongSoBienBanHoiCungCoGhiAm',
    kind: 'number',
    type: 'number',
    labels: ['Tổng số biên bản hỏi cung có ghi âm ghi hình'],
  },
  {
    key: 'statistic.tongTienPhatHanhChinh',
    column: 'statistic.tongTienPhatHanhChinh',
    kind: 'number',
    type: 'number',
    labels: ['Tổng số tiền phạt hành chính (triệu Việt Nam Đồng)'],
  },
  {
    key: 'statistic.vksYeuCauGhiAm',
    column: 'statistic.vksYeuCauGhiAm',
    kind: 'toggle',
    type: 'toggle',
    labels: ['Bấm xác nhận nếu VKS yêu cầu ghi âm ghi hình'],
  },
  {
    key: 'statistic.vuAnDaDuocXetXu',
    column: 'statistic.vuAnDaDuocXetXu',
    kind: 'toggle',
    type: 'toggle',
    labels: ['Xác nhận vụ án đã được xét xử'],
  },
  {
    key: 'supervisingUnit',
    column: 'donViGiaiQuyet',
    kind: 'fk',
    type: 'String?',
    labels: ['Đơn vị giải quyết'],
  },
  {
    key: 'tdcKhacPhucBienBan',
    column: 'tdcKhacPhucBienBan',
    kind: 'textarea',
    type: 'String?',
    labels: ['Biên bản, báo cáo, kế hoạch khắc phục lý do TĐC vụ án'],
  },
  {
    key: 'tdcKhacPhucLyDoBienPhap',
    column: 'tdcKhacPhucLyDoBienPhap',
    kind: 'textarea',
    type: 'String?',
    labels: ['Biện pháp, tiến độ khắc phục lý do TĐC vụ án'],
  },
  {
    key: 'tenCungCap',
    column: 'tenCungCap',
    kind: 'text',
    type: 'String?',
    labels: ['Tên cá nhân, cơ quan, tổ chức cung cấp, bị hại'],
  },
  {
    key: 'tienDoKhacPhucTDCVuViec',
    column: 'tienDoKhacPhucTDCVuViec',
    kind: 'textarea',
    type: 'String?',
    labels: ['Tiến độ khắc phục TĐC vụ việc'],
  },
  {
    key: 'toiDanhBanDau',
    column: 'toiDanhBanDau',
    kind: 'text',
    type: 'String?',
    labels: ['Tội danh cũ trước đây'],
  },
  {
    key: 'toiDanhChinhKhoiToId',
    column: 'toiDanhChinhKhoiToId',
    kind: 'crime',
    type: 'String?',
    labels: ['Tội danh chính khi khởi tố'],
  },
  {
    key: 'toiDanhKhacIds',
    column: 'toiDanhKhacIds',
    kind: 'multiselect',
    type: 'String[]',
    labels: ['Tội danh phụ khi khởi tố'],
  },
  {
    key: 'utdt_thoiHanUyThac',
    column: 'thoiHanUyThac',
    kind: 'date',
    type: 'DateTime?',
    labels: ['Thời hạn thực hiện Uỷ thác điều tra'],
  },
  {
    key: 'vatChungMoTa',
    column: 'vatChungMoTa',
    kind: 'textarea',
    type: 'String?',
    labels: ['Loại, đặc điểm đồ vật, tài liệu, vật chứng'],
  },
  {
    key: 'vuViecTamDungTruoc2015',
    column: 'vuViecTamDungTruoc2015',
    kind: 'toggle',
    type: 'Boolean?',
    labels: [
      'Xác định vụ việc này là vụ việc tạm dừng giải quyết (trước năm 2015)',
    ],
  },
] as const;
