/**
 * Unit tests for generate-shared-enums.cjs codegen helpers.
 *
 * Uses Node's built-in test runner (node:test). Run:
 *   node --test backend/scripts/__tests__/generate-shared-enums.test.cjs
 *
 * v0.67 PR1 T1 — add VALID_TRANSITIONS codegen (Issue I1 from /plan-eng-review).
 */
const { test } = require('node:test');
const assert = require('node:assert');
const {
  extractValidTransitions,
  emitTransitionsTypeScript,
} = require('../generate-shared-enums.cjs');

test('extractValidTransitions parses a single status with multiple targets', () => {
  const source = `
export const VALID_TRANSITIONS: Record<string, IncidentStatus[]> = {
  [IncidentStatus.TIEP_NHAN]: [
    IncidentStatus.DANG_XAC_MINH,
    IncidentStatus.DA_PHAN_CONG,
  ],
};
`;
  const result = extractValidTransitions(source);
  assert.deepStrictEqual(result.TIEP_NHAN, ['DANG_XAC_MINH', 'DA_PHAN_CONG']);
});

test('extractValidTransitions parses multiple statuses', () => {
  const source = `
export const VALID_TRANSITIONS: Record<string, IncidentStatus[]> = {
  [IncidentStatus.TIEP_NHAN]: [
    IncidentStatus.DANG_XAC_MINH,
  ],
  [IncidentStatus.DANG_XAC_MINH]: [
    IncidentStatus.DA_PHAN_CONG,
    IncidentStatus.KHONG_KHOI_TO,
  ],
};
`;
  const result = extractValidTransitions(source);
  assert.deepStrictEqual(result.TIEP_NHAN, ['DANG_XAC_MINH']);
  assert.deepStrictEqual(result.DANG_XAC_MINH, ['DA_PHAN_CONG', 'KHONG_KHOI_TO']);
});

test('extractValidTransitions returns empty object when no VALID_TRANSITIONS in source', () => {
  const source = `export const OTHER_THING = {};`;
  const result = extractValidTransitions(source);
  assert.deepStrictEqual(result, {});
});

test('emitTransitionsTypeScript produces typed Record literal', () => {
  const map = {
    TIEP_NHAN: ['DANG_XAC_MINH', 'DA_PHAN_CONG'],
    DANG_XAC_MINH: ['KHONG_KHOI_TO'],
  };
  const result = emitTransitionsTypeScript(map);
  assert.ok(result.includes('INCIDENT_VALID_TRANSITIONS'));
  assert.ok(result.includes("TIEP_NHAN: ['DANG_XAC_MINH', 'DA_PHAN_CONG']"));
  assert.ok(result.includes("DANG_XAC_MINH: ['KHONG_KHOI_TO']"));
  assert.ok(result.includes('as const'));
});

test('emitTransitionsTypeScript includes auto-generated header', () => {
  const result = emitTransitionsTypeScript({ TIEP_NHAN: [] });
  assert.ok(/auto-generated|AUTO-GENERATED|generated by/i.test(result));
});
