-- Field-parity đầy đủ: promote MỌI field hệ cũ có data → cột typed (đúng nghĩa/giai đoạn).
-- Additive, idempotent (IF NOT EXISTS). Backfill dữ liệu ở cli/backfill-parity.ts.

-- petitions
ALTER TABLE "petitions" ADD COLUMN IF NOT EXISTS "phanLoaiToiPhamLinhVuc" TEXT;
ALTER TABLE "petitions" ADD COLUMN IF NOT EXISTS "phanLoaiHoSoNoiBo" TEXT;
ALTER TABLE "petitions" ADD COLUMN IF NOT EXISTS "ghiChuKhac" TEXT;
ALTER TABLE "petitions" ADD COLUMN IF NOT EXISTS "yeuCauBoSung" TEXT;
ALTER TABLE "petitions" ADD COLUMN IF NOT EXISTS "soTienBiThietHai" INTEGER;
ALTER TABLE "petitions" ADD COLUMN IF NOT EXISTS "soLuongBiHai" INTEGER;

-- incidents
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "nhanXet" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ngayTiepNhanNguonTin" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "loaiThongTin" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ngayVietDon" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ghiChuTrungDon" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "baoCaoBanGiamDoc" BOOLEAN;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ngayGiaoDonViGiaiQuyet" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "toiDanhBanDau" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "soPhieuChuyen" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ngayPhieuChuyen" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "doVatTaiLieuKemTheo" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "phanLoaiToiPhamLinhVuc" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "phanLoaiHoSoNoiBo" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "lanhDaoToTung" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "dieuTraVien" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "dieuTraVienPhuongXa" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "noiCapCccd" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ngayCapCccd" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "deXuat" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "yeuCauBoSung" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ghiChuKhac" TEXT;

-- cases
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ngayDeXuat" TIMESTAMP(3);
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "moTaChiTiet" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "nguonDon" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "tenCungCap" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "sinhNamCungCap" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "cccdCungCap" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ngayCapCccd" TIMESTAMP(3);
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "noiCapCccd" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "sdtCungCap" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "diaChiCungCap" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "nghiVanDoiTuong" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "nhanXet" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "noiXayRa" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "phuongThucThuDoan" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ketQuaXuLyKhac" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "soPhieuChuyen" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ngayPhieuChuyen" TIMESTAMP(3);
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "doVatTaiLieuKemTheo" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ngayVietDon" TIMESTAMP(3);
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ghiChuTrungDon" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "baoCaoBanGiamDoc" BOOLEAN;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "ngayGiaoDonViGiaiQuyet" TIMESTAMP(3);
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "lanhDaoToTung" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "dieuTraVien" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "phanLoaiToiPhamLinhVuc" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "phanLoaiHoSoNoiBo" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "deXuat" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "yeuCauBoSung" TEXT;
