-- 4a: số QĐ giai đoạn vụ án (cột Case, nullable). 4b/4c: bảng case_statistics (hybrid). Plain DDL.
ALTER TABLE "cases"
  ADD COLUMN "soQuyetDinhKhoiTo" TEXT,
  ADD COLUMN "soQDNhapVuAn" TEXT,
  ADD COLUMN "ngayNhapVuAn" TIMESTAMP(3),
  ADD COLUMN "ghiChuNhapHoSo" TEXT,
  ADD COLUMN "soQDTachVuAn" TEXT,
  ADD COLUMN "ngayTachVuAn" TIMESTAMP(3),
  ADD COLUMN "soQDTachHanhVi" TEXT,
  ADD COLUMN "ngayTachHanhVi" TIMESTAMP(3),
  ADD COLUMN "soQDDinhChiVuAn" TEXT,
  ADD COLUMN "ngayDinhChiVuAn" TIMESTAMP(3),
  ADD COLUMN "chuyenVuAnChoCQK" TEXT,
  ADD COLUMN "soBanAnCoHieuLuc" TEXT,
  ADD COLUMN "ngayBanAnCoHieuLuc" TIMESTAMP(3),
  ADD COLUMN "canCuTamDinhChiVuAn" TEXT,
  ADD COLUMN "canCuPhucHoiVuAn" TEXT;

CREATE TABLE "case_statistics" (
  "id" TEXT NOT NULL,
  "caseId" TEXT NOT NULL,
  "soDangKyHoSo" TEXT,
  "ngayDangKyHoSo" TIMESTAMP(3),
  "hoSoLuu" TEXT,
  "ngayNopLuuHoSo" TIMESTAMP(3),
  "donViBaoQuanHoSo" TEXT,
  "coGhiAmGhiHinh" BOOLEAN NOT NULL DEFAULT false,
  "tongSoBienBanGhiLoiKhai" INTEGER,
  "soBienBanGhiLoiKhaiCoGhiAm" INTEGER,
  "laVuAnGhiAmGhiHinh" BOOLEAN NOT NULL DEFAULT false,
  "tongSoBienBanHoiCung" INTEGER,
  "tongSoBienBanHoiCungCoGhiAm" INTEGER,
  "soBiCanCoGhiAm" INTEGER,
  "vksYeuCauGhiAm" BOOLEAN NOT NULL DEFAULT false,
  "soBiCanVksYeuCauGhiAm" INTEGER,
  "coVPHC" BOOLEAN NOT NULL DEFAULT false,
  "soDoiTuongVPHC" INTEGER,
  "soNguoiBiPhatTien" INTEGER,
  "tongTienPhatHanhChinh" DOUBLE PRECISION,
  "soDoiTuongDaBat" INTEGER,
  "soDoiTuongBiBatVuAnKhac" INTEGER,
  "dieuTraMoRong" INTEGER,
  "suDungVuKhiNong" TEXT,
  "coBangNhom" BOOLEAN NOT NULL DEFAULT false,
  "soBangNhomBatDuoc" INTEGER,
  "soSungThuHoi" INTEGER,
  "soThuocNoThuHoi" INTEGER,
  "soDoiTuongSuuTraHiemNghi" INTEGER,
  "ngayThongKe" TIMESTAMP(3),
  "ngayPhanCongGiaiQuyetToGiac" TIMESTAMP(3),
  "ngayTiepNhanTin" TIMESTAMP(3),
  "ngayDauThu" TIMESTAMP(3),
  "ngayPhamToiQuaTang" TIMESTAMP(3),
  "ngayBatKhanCap" TIMESTAMP(3),
  "ngayPhatHienDauHieu" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "case_statistics_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "case_statistics_caseId_key" ON "case_statistics"("caseId");
ALTER TABLE "case_statistics" ADD CONSTRAINT "case_statistics_caseId_fkey"
  FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE CASCADE;
